// Alpha Husky — Relay Fringe 01 local Phaser slice.
// This room deliberately has no rewards, writes, pickups, or progression authority.
(function (global) {
  "use strict";

  const ROOT_ID = "alphaExplorationRoom";
  const CANVAS_ID = "alphaExplorationRoomCanvas";
  const STYLE_ID = "ah-exploration-room-css";
  const SECTOR_ID = "relay_fringe_01";
  const WORLD_WIDTH = 1400;
  const WORLD_HEIGHT = 900;
  const PLAYER_SPEED = 230;
  const PLAYER_MAX_HP = 3;
  const SENTINEL_MAX_HP = 6;
  const ATTACK_COOLDOWN_MS = 500;
  const DASH_COOLDOWN_MS = 1750;
  const DASH_DURATION_MS = 150;
  const DASH_SPEED = 560;
  const MELEE_OFFSET = 58;
  const MELEE_RADIUS = 42;
  const SENTINEL_HIT_RADIUS = 32;
  const SENTINEL_VISUAL = Object.freeze({ scale: .14, originY: .92, groundOffsetY: 29, bodySize: 58 });
  const BARRIER_VISUAL = Object.freeze({ scale: .14, originX: .507, originY: .541, rotation: Math.PI / 2, bodyWidth: 54, bodyHeight: 142 });
  const ARENA = Object.freeze({ left: 744, right: 1188, top: 248, bottom: 682, gateY: 465, gateHeight: 142, triggerX: 806, triggerY: 465, triggerWidth: 82, triggerHeight: 176, sentinelX: 978, sentinelY: 465 });
  const NODE_RANGE_SQ = 150 * 150;
  const RELAY_NODE_RANGE_SQ = 116 * 116;
  const EXIT_RANGE_SQ = 126 * 126;
  const READY_TIMEOUT_MS = 9000;
  const PLAYER_SHEET = "ah-relay-player-sheet-v1";
  const PLAYER_SHEET_URL = "assets/dojo/v1/processed/alpha_husky_player_sheet_v1.png";
  const ASSETS = Object.freeze({
    floor: { key: "ah-relay-floor", url: "assets/world_exploration/relay_fringe_01/relay_floor.webp" },
    relayNodeIdle: { key: "ah-relay-node-idle", url: "assets/world_exploration/relay_fringe_01/dead_relay_node_idle.webp" },
    relayNodeActive: { key: "ah-relay-node-active", url: "assets/world_exploration/relay_fringe_01/dead_relay_node_active.webp" },
    sentinelIdle: { key: "ah-relay-sentinel-idle", url: "assets/world_exploration/relay_fringe_01/relay_sentinel_idle.webp" },
    sentinelAttack: { key: "ah-relay-sentinel-attack", url: "assets/world_exploration/relay_fringe_01/relay_sentinel_attack.webp" },
    sentinelDefeated: { key: "ah-relay-sentinel-defeated", url: "assets/world_exploration/relay_fringe_01/relay_sentinel_defeated.webp" },
    duelBarrier: { key: "ah-relay-duel-barrier", url: "assets/world_exploration/relay_fringe_01/relay_duel_barrier.webp" },
    wall: { key: "ah-relay-wall", url: "assets/dojo/v1/processed/wall.webp" },
    verticalWall: { key: "ah-relay-vertical-wall", url: "assets/dojo/v1/processed/vertical_wall.webp" },
    exitGate: { key: "ah-relay-exit", url: "assets/dojo/v1/processed/exit_gate.webp" },
  });
  const S = {
    tg: null, dbg: false, trace: null, devPreview: false, root: null, canvasParent: null, loading: null, game: null, scene: null,
    opening: null, closing: false, ready: false, generation: 0, resolveReady: null, rejectReady: null,
    readyTimer: null, diagnosticTimer: null, canvas: null, pageStyles: null, navRegistered: false, onClose: null,
    safeInsets: { top: 0, right: 0, bottom: 0, left: 0 },
  };

  function log(message, error) { if (S.dbg) try { console.debug("[ExplorationRoom] " + message, error || ""); } catch (_) {} }
  function trace(stage) { if(S.devPreview&&S.loading)S.loading.textContent=`ENTERING SIGNAL APPROACH... DEV STAGE: ${stage}`;try { (S.trace || global.__AH_RELAY_STARTUP_TRACE)?.(stage); } catch (_) {} }
  function isTouch() { return !!global.matchMedia?.("(pointer: coarse)")?.matches; }
  function injectCSS() {
    if (document.getElementById(STYLE_ID)) return;
    const style = document.createElement("style"); style.id = STYLE_ID;
    style.textContent = `
.ah-exploration-room{position:fixed;inset:0;z-index:12060;display:grid;grid-template-rows:auto minmax(0,1fr);height:100dvh;overflow:hidden;background:#05090d;color:#e8f3ff;font-family:Inter,system-ui,sans-serif;touch-action:none;overscroll-behavior:none}
.ah-exploration-room__header{min-height:56px;display:grid;grid-template-columns:76px minmax(0,1fr) 76px;align-items:center;gap:8px;padding:max(8px,env(safe-area-inset-top)) max(10px,env(safe-area-inset-right)) 8px max(10px,env(safe-area-inset-left));background:linear-gradient(#111a23,#091018);border-bottom:1px solid rgba(101,232,255,.24)}
.ah-exploration-room__back{min-height:40px;border:1px solid rgba(151,188,207,.3);border-radius:9px;background:#101a25;color:#dcecff;font:700 11px/1 system-ui;letter-spacing:.08em;text-transform:uppercase;touch-action:manipulation}.ah-exploration-room__heading{text-align:center;min-width:0}.ah-exploration-room__heading span{display:block;color:#7f96a8;font-size:9px;font-weight:800;letter-spacing:.17em}.ah-exploration-room__heading strong{display:block;margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:15px;letter-spacing:.04em}.ah-exploration-room__seal{color:#65e8ff;text-align:center;font-size:10px;letter-spacing:.12em}
.ah-exploration-room__stage,.ah-exploration-room__canvas{position:relative;min-width:0;min-height:0;overflow:hidden;touch-action:none}.ah-exploration-room__canvas{position:absolute;inset:0}.ah-exploration-room__canvas canvas{display:block!important;width:100%!important;height:100%!important;touch-action:none!important}.ah-exploration-room__loading{position:absolute;inset:0;display:grid;place-items:center;background:radial-gradient(circle at 50% 44%,rgba(26,76,92,.22),transparent 45%),#071019;color:#9cb2c3;font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;pointer-events:none}
.ah-exploration-room__loading[hidden]{display:none!important;pointer-events:none!important}.ah-exploration-room__diagnostic{position:absolute;right:8px;top:calc(env(safe-area-inset-top) + 8px);z-index:4;max-width:calc(100% - 16px);padding:5px 7px;border:1px solid rgba(101,232,255,.38);background:rgba(4,12,18,.86);color:#baf6ff;font:800 9px/1.35 ui-monospace,monospace;letter-spacing:.03em;pointer-events:none;white-space:pre-wrap}
@media(max-width:380px){.ah-exploration-room__header{grid-template-columns:66px minmax(0,1fr) 54px}.ah-exploration-room__back{font-size:10px}.ah-exploration-room__seal{font-size:8px}}
`; document.head.appendChild(style);
  }
  function buildShell() {
    const existing = document.getElementById(ROOT_ID);
    const root = existing || document.createElement("section"); root.id = ROOT_ID; root.className = "ah-exploration-room"; root.style.cssText = "";
    root.setAttribute("role", "dialog"); root.setAttribute("aria-modal", "true"); root.setAttribute("aria-label", "Relay Fringe 01 Signal Approach");
    root.innerHTML = `<header class="ah-exploration-room__header"><button type="button" class="ah-exploration-room__back" data-exploration-room-action="back">Back</button><div class="ah-exploration-room__heading"><span>RELAY FRINGE 01</span><strong>SIGNAL APPROACH</strong></div><span class="ah-exploration-room__seal">LOCAL</span></header><div class="ah-exploration-room__stage"><div id="${CANVAS_ID}" class="ah-exploration-room__canvas"></div><div class="ah-exploration-room__loading" role="status">Entering signal approach…</div></div>`;
    if (!root.isConnected) document.body.appendChild(root); S.root = root; S.canvasParent = root.querySelector("#" + CANVAS_ID); S.loading = root.querySelector(".ah-exploration-room__loading");
  }
  function lockPage() { if (S.pageStyles) return; const b = document.body.style, h = document.documentElement.style; S.pageStyles = { bo:b.overflow, bt:b.touchAction, bs:b.overscrollBehavior, ho:h.overflow, ht:h.touchAction, hs:h.overscrollBehavior }; b.overflow = h.overflow = "hidden"; b.touchAction = h.touchAction = "none"; b.overscrollBehavior = h.overscrollBehavior = "none"; }
  function restorePage() { if (!S.pageStyles) return; const v=S.pageStyles,b=document.body.style,h=document.documentElement.style; b.overflow=v.bo;b.touchAction=v.bt;b.overscrollBehavior=v.bs;h.overflow=v.ho;h.touchAction=v.ht;h.overscrollBehavior=v.hs;S.pageStyles=null; }
  function readInsets() { if (!S.root) return; const p=document.createElement("i");p.style.cssText="position:absolute;visibility:hidden;padding:env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left)";S.root.appendChild(p);const c=getComputedStyle(p);S.safeInsets={top:parseFloat(c.paddingTop)||0,right:parseFloat(c.paddingRight)||0,bottom:parseFloat(c.paddingBottom)||0,left:parseFloat(c.paddingLeft)||0};p.remove(); }
  function registerNavigation() { if (!global.AlphaNav?.push) return; global.AlphaNav.push(ROOT_ID,{close:()=>void close({fromNavigation:true}),isOpen,fallback:false});S.navRegistered=true; }
  function unregisterNavigation(fromNavigation) { if (!S.navRegistered) return; if (!fromNavigation) try { global.navClose?.(ROOT_ID); } catch (_) {} try { global.navUnregister?.(ROOT_ID); } catch (_) {} S.navRegistered=false; }
  function onResize() { if (!S.game || !S.canvasParent) return; readInsets(); const w=Math.max(1,S.canvasParent.clientWidth||global.innerWidth||1),h=Math.max(1,S.canvasParent.clientHeight||global.innerHeight||1); try { S.game.scale.resize(w,h); S.scene?.ahLayout?.(w,h,S.safeInsets); } catch (error) { log("resize failed",error); } }
  function onVisibility() { const scene=S.scene;if(!scene)return;if(document.hidden){scene.ahPaused=true;scene.ahResetInput?.();scene.ahStop?.();if(scene.input)scene.input.enabled=false;try{scene.physics.world.pause();}catch(_){}}else if(scene.ahPaused&&!S.closing){scene.ahPaused=false;scene.ahResetInput?.();try{scene.physics.world.resume();}catch(_){}if(scene.input)scene.input.enabled=true;} }
  function onWindowBlur() { const scene=S.scene;scene?.ahResetInput?.();scene?.ahStop?.(); }
  function bindEvents() { S.root.addEventListener("click",onRootClick);global.addEventListener("resize",onResize);global.addEventListener("blur",onWindowBlur);document.addEventListener("visibilitychange",onVisibility);try{S.tg?.onEvent?.("viewportChanged",onResize);}catch(_){} }
  function unbindEvents() { S.root?.removeEventListener("click",onRootClick);global.removeEventListener("resize",onResize);global.removeEventListener("blur",onWindowBlur);document.removeEventListener("visibilitychange",onVisibility);try{S.tg?.offEvent?.("viewportChanged",onResize);}catch(_){}S.canvas?.removeEventListener("pointercancel",resetPointer);S.canvas=null; }
  function onRootClick(event) { if(event.target.closest?.("[data-exploration-room-action='back']")) void close(); }
  function resetPointer() { S.scene?.ahResetInput?.();S.scene?.ahStop?.(); }

  function makePlayerAnimations(scene) {
    if (!scene.textures.exists(PLAYER_SHEET)) return false;
    ["down","up","right","left"].forEach((dir,row)=>{ const idle="ah-relay-"+dir+"-idle",walk="ah-relay-"+dir+"-walk"; if(!scene.anims.exists(idle))scene.anims.create({key:idle,frames:[{key:PLAYER_SHEET,frame:row*4}],repeat:-1}); if(!scene.anims.exists(walk))scene.anims.create({key:walk,frames:[row*4+1,row*4+2,row*4+3,row*4+2].map(frame=>({key:PLAYER_SHEET,frame})),frameRate:7,repeat:-1}); }); return true;
  }
  function setAnimation(scene, direction, moving) { const key="ah-relay-"+(direction||scene.ahDirection||"down")+(moving?"-walk":"-idle");scene.ahDirection=direction||scene.ahDirection||"down";if(scene.ahPlayer?.anims?.currentAnim?.key!==key)scene.ahPlayer?.play?.(key); }
  function addVisibleBlock(scene, group, x, y, width, height, fill=0x182630, stroke=0x416173) { const block=scene.add.rectangle(x,y,width,height,fill,1).setStrokeStyle(2,stroke,.85).setDepth(9);scene.physics.add.existing(block,true);group.add(block);return block; }
  function addWall(scene, group, x, y, width, height) { const asset=ASSETS.wall;if(scene.textures.exists(asset.key)){const image=scene.add.image(x,y,asset.key).setScale(.25).setDepth(10);const body=addVisibleBlock(scene,group,x,y+4,Math.min(width,218),height,0x20313b,0x6292a1);body.setAlpha(.72);return image;}return addVisibleBlock(scene,group,x,y,width,height); }
  function buildFloor(scene) { if(scene.textures.exists(ASSETS.floor.key)){[351,1053].forEach(x=>[351,1053].forEach(y=>scene.add.image(x,y,ASSETS.floor.key).setScale(.56).setDepth(0)));}else{const g=scene.add.graphics();g.fillStyle(0x0b151d,1);g.fillRect(0,0,WORLD_WIDTH,WORLD_HEIGHT);g.lineStyle(1,0x28434e,.32);for(let x=40;x<WORLD_WIDTH;x+=80)g.lineBetween(x,0,x,WORLD_HEIGHT);for(let y=40;y<WORLD_HEIGHT;y+=80)g.lineBetween(0,y,WORLD_WIDTH,y);} const signal=scene.add.graphics().setDepth(2);signal.lineStyle(2,0x48c8df,.18);signal.strokeRect(76,76,WORLD_WIDTH-152,WORLD_HEIGHT-152);signal.lineStyle(2,0xd19b52,.22);signal.strokeLineShape(new global.Phaser.Geom.Line(170,712,1110,712)); }
  function addNode(scene) { const x=1010,y=344,idleLoaded=scene.textures.exists(ASSETS.relayNodeIdle.key),activeLoaded=scene.textures.exists(ASSETS.relayNodeActive.key);let node;if(idleLoaded||activeLoaded){node=scene.add.image(x,y,idleLoaded?ASSETS.relayNodeIdle.key:ASSETS.relayNodeActive.key).setScale(.16).setDepth(14);scene.ahNodeUsesImage=true;}else{node=scene.add.rectangle(x,y+2,136,150,0x172f39,.96).setStrokeStyle(3,0x54727f,.95).setDepth(14);scene.ahNodeUsesImage=false;}scene.ahNode=node;scene.ahNodeAnchor={x,y:y+66};scene.ahNodeGlow=scene.add.circle(x,y+58,78,0x65e8ff,.02).setStrokeStyle(2,0x65e8ff,.16).setDepth(13);scene.ahNodeLabel=scene.add.text(x,y-94,"DEAD RELAY NODE",{fontFamily:"system-ui",fontSize:"12px",color:"#a9edf7",fontStyle:"bold"}).setOrigin(.5).setDepth(16);scene.ahNodeState="locked";scene.ahNodeTextures={idleLoaded,activeLoaded};setNodeState(scene,"locked"); }
  function setNodeState(scene,state) { const node=scene.ahNode;if(!node)return;scene.ahNodeState=state;const textures=scene.ahNodeTextures||{};if(scene.ahNodeUsesImage){const key=state==="restored"&&textures.activeLoaded?ASSETS.relayNodeActive.key:(textures.idleLoaded?ASSETS.relayNodeIdle.key:ASSETS.relayNodeActive.key);node.setTexture(key);node.setTint(state==="locked"?0x7e8a91:0xffffff);}else{node.setFillStyle(state==="locked"?0x172f39:state==="available"?0x23505a:0x176878,.98);node.setStrokeStyle(3,state==="locked"?0x54727f:state==="available"?0x7ce9f4:0xb7fbff,.95);}scene.ahNodeGlow.setAlpha(state==="locked" ? .02 : state==="available" ? .13 : .32).setStrokeStyle(2,state==="restored"?0xb7fbff:0x65e8ff,state==="locked" ? .16 : .78);scene.ahNodeLabel.setColor(state==="locked"?"#8297a2":state==="available"?"#a9edf7":"#c7fbff"); }
  function restoreSignal(scene) { if(scene.ahNodeState!=="available")return;setNodeState(scene,"restored");scene.ahSignalRestored=true;scene.events.emit("relay-signal-restored",{sectorId:SECTOR_ID});const pulse=scene.add.circle(scene.ahNodeAnchor.x,scene.ahNodeAnchor.y,36,0x65e8ff,.48).setDepth(25);scene.ahNodePulse=pulse;scene.tweens.add({targets:pulse,scale:3,alpha:0,duration:560,onComplete:()=>pulse.destroy()});later(scene,600,()=>{if(scene.ahNodePulse===pulse)scene.ahNodePulse=null;});setContext(scene,null);showMessage(scene,"SIGNAL RESTORED"); }
  function addExit(scene) { const x=1232,y=692;scene.ahExit={x,y};if(scene.textures.exists(ASSETS.exitGate.key))scene.add.image(x,y,ASSETS.exitGate.key).setScale(.22).setDepth(12);else{scene.add.rectangle(x,y,150,82,0x173b44,.65).setStrokeStyle(2,0x65e8ff,.8).setDepth(12);scene.add.text(x,y,"EXIT // MAP",{fontFamily:"system-ui",fontSize:"14px",color:"#baf6ff",fontStyle:"bold"}).setOrigin(.5).setDepth(13);} }
  function addArena(scene) {
    const walls=scene.physics.add.staticGroup(), mid=(ARENA.top+ARENA.bottom)/2, gapTop=ARENA.gateY-ARENA.gateHeight/2, gapBottom=ARENA.gateY+ARENA.gateHeight/2;scene.ahArenaWalls=walls;
    addVisibleBlock(scene,walls,(ARENA.left+ARENA.right)/2,ARENA.top,ARENA.right-ARENA.left,34,0x14222c,0x65e8ff);
    addVisibleBlock(scene,walls,(ARENA.left+ARENA.right)/2,ARENA.bottom,ARENA.right-ARENA.left,34,0x14222c,0x65e8ff);
    addVisibleBlock(scene,walls,ARENA.right,mid,34,ARENA.bottom-ARENA.top,0x14222c,0x65e8ff);
    addVisibleBlock(scene,walls,ARENA.left,(ARENA.top+gapTop)/2,34,gapTop-ARENA.top,0x14222c,0x65e8ff);
    addVisibleBlock(scene,walls,ARENA.left,(gapBottom+ARENA.bottom)/2,34,ARENA.bottom-gapBottom,0x14222c,0x65e8ff);
    scene.physics.add.collider(scene.ahPlayer,walls);
    scene.ahArenaFrame=scene.add.rectangle((ARENA.left+ARENA.right)/2,mid,ARENA.right-ARENA.left-36,ARENA.bottom-ARENA.top-36,0x65e8ff,.018).setStrokeStyle(2,0x65e8ff,.24).setDepth(3);
    scene.ahTrigger=scene.add.rectangle(ARENA.triggerX,ARENA.triggerY,ARENA.triggerWidth,ARENA.triggerHeight,0xd19b52,.10).setStrokeStyle(2,0xd19b52,.58).setDepth(4);
    scene.add.text(ARENA.triggerX,ARENA.triggerY-112,"HOSTILE SIGNAL",{fontFamily:"system-ui",fontSize:"11px",color:"#d9b77f",fontStyle:"bold"}).setOrigin(.5).setDepth(6);
    scene.ahBarrier=scene.add.rectangle(ARENA.left,ARENA.gateY,BARRIER_VISUAL.bodyWidth,BARRIER_VISUAL.bodyHeight,0x5eeaff,.26).setStrokeStyle(3,0x9ff7ff,.95).setDepth(18);
    scene.physics.add.existing(scene.ahBarrier,true);scene.ahBarrier.body.enable=false;scene.ahBarrierCollider=scene.physics.add.collider(scene.ahPlayer,scene.ahBarrier);
    if(scene.textures.exists(ASSETS.duelBarrier.key))scene.ahBarrierVisual=scene.add.image(ARENA.left,ARENA.gateY,ASSETS.duelBarrier.key).setOrigin(BARRIER_VISUAL.originX,BARRIER_VISUAL.originY).setScale(BARRIER_VISUAL.scale).setRotation(BARRIER_VISUAL.rotation).setDepth(19).setVisible(false);
    scene.ahBarrier.setAlpha(.28);
  }
  function setBarrier(scene, active) { const barrier=scene.ahBarrier;if(!barrier)return;barrier.body.enable=!!active;barrier.refreshBody?.();const visual=scene.ahBarrierVisual;if(visual){visual.setVisible(!!active).setAlpha(active?1:0);barrier.setVisible(!active).setAlpha(active?0:.28);if(active)scene.tweens.add({targets:visual,alpha:{from:.55,to:1},duration:180,yoyo:true});}else{barrier.setVisible(true).setAlpha(active?1:.28);barrier.setFillStyle(active ? 0x3ccfe7 : 0x5eeaff, active ? .68 : .26);if(active)scene.tweens.add({targets:barrier,alpha:{from:.55,to:1},duration:180,yoyo:true});} }
  function setSentinelVisual(scene,state){const visual=scene.ahSentinelVisual;if(!visual)return;const textures=scene.ahSentinelTextures||{},fallbackDefeated=state==="defeated"&&!textures.defeated,key=state==="lunge"?(textures.attack?ASSETS.sentinelAttack.key:textures.idle?ASSETS.sentinelIdle.key:null):state==="defeated"?(textures.defeated?ASSETS.sentinelDefeated.key:textures.idle?ASSETS.sentinelIdle.key:null):(textures.idle?ASSETS.sentinelIdle.key:null);if(!key){visual.setVisible(false);scene.ahSentinel?.setVisible(true);return;}visual.setTexture(key).setVisible(true).setAlpha(state==="dormant" ? .32 : fallbackDefeated ? .68 : 1).setTint(fallbackDefeated?0x6d8890:state==="telegraph"?0xffdce2:0xffffff);scene.ahSentinel?.setVisible(false);}
  function syncSentinelVisual(scene){const visual=scene.ahSentinelVisual,s=scene.ahSentinel;if(visual?.visible&&s)visual.setPosition(s.x,s.y+SENTINEL_VISUAL.groundOffsetY);}
  function addSentinel(scene) { const body=scene.add.rectangle(ARENA.sentinelX,ARENA.sentinelY,64,64,0x6a2337,.55).setStrokeStyle(3,0xff6b86,.8).setDepth(27);scene.physics.add.existing(body);body.body.setSize(SENTINEL_VISUAL.bodySize,SENTINEL_VISUAL.bodySize);scene.physics.add.collider(body,scene.ahArenaWalls);scene.ahSentinelTextures={idle:scene.textures.exists(ASSETS.sentinelIdle.key),attack:scene.textures.exists(ASSETS.sentinelAttack.key),defeated:scene.textures.exists(ASSETS.sentinelDefeated.key)};if(scene.ahSentinelTextures.idle||scene.ahSentinelTextures.attack||scene.ahSentinelTextures.defeated)scene.ahSentinelVisual=scene.add.image(ARENA.sentinelX,ARENA.sentinelY+SENTINEL_VISUAL.groundOffsetY,scene.ahSentinelTextures.idle?ASSETS.sentinelIdle.key:scene.ahSentinelTextures.attack?ASSETS.sentinelAttack.key:ASSETS.sentinelDefeated.key).setOrigin(.5,SENTINEL_VISUAL.originY).setScale(SENTINEL_VISUAL.scale).setDepth(27);body.setVisible(!scene.ahSentinelVisual).setAlpha(.32);scene.ahSentinelFallbackGlow=scene.add.circle(ARENA.sentinelX,ARENA.sentinelY,48,0xff4e70,.04).setStrokeStyle(2,0xff6580,.24).setDepth(25).setVisible(!scene.ahSentinelVisual);scene.ahSentinel=body;scene.ahSentinelSpawn={x:ARENA.sentinelX,y:ARENA.sentinelY};scene.ahSentinelActive=false;setSentinelVisual(scene,"dormant"); }
  function buildWorld(scene) {
    buildFloor(scene); const blockers=scene.physics.add.staticGroup();
    addVisibleBlock(scene,blockers,WORLD_WIDTH/2,25,WORLD_WIDTH,50,0x111c25,0x385468);addVisibleBlock(scene,blockers,WORLD_WIDTH/2,WORLD_HEIGHT-25,WORLD_WIDTH,50,0x111c25,0x385468);addVisibleBlock(scene,blockers,25,WORLD_HEIGHT/2,50,WORLD_HEIGHT,0x111c25,0x385468);addVisibleBlock(scene,blockers,WORLD_WIDTH-25,WORLD_HEIGHT/2,50,WORLD_HEIGHT,0x111c25,0x385468);
    // Main route with one optional upper recess. Every physical blocker is visibly drawn.
    addWall(scene,blockers,406,634,222,42);addWall(scene,blockers,606,420,194,42);addWall(scene,blockers,824,592,220,42);addWall(scene,blockers,1110,470,180,42);
    addVisibleBlock(scene,blockers,708,218,44,212,0x1b2b35,0x527d8b);addVisibleBlock(scene,blockers,908,192,44,184,0x1b2b35,0x527d8b);addVisibleBlock(scene,blockers,1072,754,176,46,0x1b2b35,0x527d8b);
    scene.add.text(110,108,"PACK BOUNDARY // SIGNAL APPROACH",{fontFamily:"system-ui",fontSize:"14px",color:"#7190a0",letterSpacing:2}).setDepth(3);scene.add.text(112,800,"LOCAL DISCOVERY // NO REWARDS",{fontFamily:"system-ui",fontSize:"12px",color:"#667a86",letterSpacing:1}).setDepth(3);
    addNode(scene,blockers);addExit(scene);
    const hasSheet=makePlayerAnimations(scene);if(hasSheet){scene.ahPlayer=scene.physics.add.sprite(166,700,PLAYER_SHEET,0).setScale(.32).setDepth(30);scene.ahPlayer.body.setSize(70,90).setOffset(93,150);}else{scene.ahPlayer=scene.add.rectangle(166,700,54,70,0x65e8ff,.96).setStrokeStyle(3,0xdffcff,.95).setDepth(30);scene.physics.add.existing(scene.ahPlayer);scene.ahPlayer.body.setSize(54,70);scene.ahPlayerFallback=true;}scene.ahPlayer.body.setCollideWorldBounds(true);scene.ahDirection="right";setAnimation(scene,"right",false);scene.physics.add.collider(scene.ahPlayer,blockers);if(scene.ahNode?.body)scene.physics.add.collider(scene.ahPlayer,scene.ahNode);
    addArena(scene);addSentinel(scene);
  }
  function createControls(scene) {
    scene.ahMove=new global.Phaser.Math.Vector2();scene.ahJoy={x:0,y:0};scene.ahJoyPointer=null;scene.ahAttackPointer=null;scene.ahDashPointer=null;scene.ahRestorePointer=null;scene.ahContext=null;scene.ahPaused=false;scene.ahTouch=isTouch();scene.ahTimers=new Set();scene.ahCombatState="precombat";scene.ahEncounterStarted=false;scene.ahSignalAccessRestored=false;scene.ahSignalRestored=false;scene.ahPlayerHP=PLAYER_MAX_HP;scene.ahSentinelHP=SENTINEL_MAX_HP;scene.ahNextAttackAt=0;scene.ahNextDashAt=0;scene.ahDashUntil=0;scene.ahPlayerControl=true;
    scene.ahJoyBase=scene.add.circle(88,88,54,0x0b1620,.75).setStrokeStyle(2,0x65e8ff,.5).setScrollFactor(0).setDepth(100);scene.ahJoyThumb=scene.add.circle(88,88,25,0x65e8ff,.3).setStrokeStyle(2,0xbaf6ff,.75).setScrollFactor(0).setDepth(101);scene.ahJoyHit=scene.add.zone(88,88,160,160).setInteractive().setScrollFactor(0).setDepth(102);
    scene.ahActionRing=scene.add.circle(0,0,42,0x123741,.88).setStrokeStyle(2,0x65e8ff,.95).setScrollFactor(0).setDepth(100).setVisible(false);scene.ahActionLabel=scene.add.text(0,0,"",{fontFamily:"system-ui",fontSize:"11px",color:"#baf6ff",fontStyle:"bold",align:"center"}).setOrigin(.5).setScrollFactor(0).setDepth(101).setVisible(false);scene.ahActionHit=scene.add.zone(0,0,92,92).setInteractive().setScrollFactor(0).setDepth(102).setVisible(false);
    scene.ahRestoreRing=scene.add.circle(0,0,40,0x17606c,.94).setStrokeStyle(2,0xb7fbff,.96).setScrollFactor(0).setDepth(106).setVisible(false);scene.ahRestoreLabel=scene.add.text(0,0,"RESTORE",{fontFamily:"system-ui",fontSize:"9px",color:"#e4feff",fontStyle:"bold"}).setOrigin(.5).setScrollFactor(0).setDepth(107).setVisible(false);scene.ahRestoreHit=scene.add.zone(0,0,92,92).setInteractive().setScrollFactor(0).setDepth(108).setVisible(false);
    scene.ahDashRing=scene.add.circle(0,0,29,0x1a3041,.92).setStrokeStyle(2,0x9ff7ff,.82).setScrollFactor(0).setDepth(103).setVisible(false);scene.ahDashLabel=scene.add.text(0,0,"DASH",{fontFamily:"system-ui",fontSize:"8px",color:"#dffcff",fontStyle:"bold"}).setOrigin(.5).setScrollFactor(0).setDepth(104).setVisible(false);scene.ahDashHit=scene.add.zone(0,0,62,62).setInteractive().setScrollFactor(0).setDepth(105).setVisible(false);
    scene.ahPrompt=scene.add.text(0,0,"",{fontFamily:"system-ui",fontSize:"12px",color:"#a9edf7",fontStyle:"bold",align:"center"}).setOrigin(.5,0).setScrollFactor(0).setDepth(102);scene.ahMessage=scene.add.text(0,0,"",{fontFamily:"system-ui",fontSize:"13px",color:"#d8fbff",fontStyle:"bold",align:"center"}).setOrigin(.5).setScrollFactor(0).setDepth(103).setVisible(false);
    scene.ahOnJoyDown=p=>{if(scene.ahJoyPointer===null&&scene.input.enabled){scene.ahJoyPointer=p.id;updateJoy(scene,p);}};scene.ahOnAttackDown=p=>{if(scene.ahAttackPointer===null&&scene.input.enabled){scene.ahAttackPointer=p.id;playerAttack(scene);}};scene.ahOnDashDown=p=>{if(scene.ahDashPointer===null&&scene.input.enabled){scene.ahDashPointer=p.id;playerDash(scene);}};scene.ahOnRestoreDown=p=>{if(scene.ahRestorePointer===null&&scene.input.enabled&&scene.ahContext==="node_available"){scene.ahRestorePointer=p.id;restoreSignal(scene);}};scene.ahOnMove=p=>{if(p.id===scene.ahJoyPointer)updateJoy(scene,p);};scene.ahOnUp=p=>{if(p.id===scene.ahJoyPointer)resetJoy(scene);if(p.id===scene.ahAttackPointer)scene.ahAttackPointer=null;if(p.id===scene.ahDashPointer)scene.ahDashPointer=null;if(p.id===scene.ahRestorePointer)scene.ahRestorePointer=null;};scene.ahOnGameOut=()=>scene.ahResetInput();scene.ahOnCombatPointer=p=>{if(!scene.ahTouch&&scene.ahCombatState==="active"&&(p.button===0||p.leftButtonDown?.()))playerAttack(scene);};scene.ahJoyHit.on("pointerdown",scene.ahOnJoyDown);scene.ahActionHit.on("pointerdown",scene.ahOnAttackDown);scene.ahDashHit.on("pointerdown",scene.ahOnDashDown);scene.ahRestoreHit.on("pointerdown",scene.ahOnRestoreDown);scene.ahActionHit.input.enabled=false;scene.ahDashHit.input.enabled=false;scene.ahRestoreHit.input.enabled=false;scene.input.on("pointermove",scene.ahOnMove);scene.input.on("pointerup",scene.ahOnUp);scene.input.on("gameout",scene.ahOnGameOut);scene.input.on("pointerdown",scene.ahOnCombatPointer);scene.ahResetJoystick=()=>resetJoy(scene);scene.ahResetInput=()=>{resetJoy(scene);scene.ahAttackPointer=null;scene.ahDashPointer=null;scene.ahRestorePointer=null;};scene.ahStop=()=>{setPlayerVelocity(scene,0,0);setAnimation(scene,scene.ahDirection,false);};scene.ahLayout=(w,h,insets)=>layout(scene,w,h,insets);layout(scene,scene.scale.width,scene.scale.height,S.safeInsets);
  }
  function layout(scene,w,h,insets) { const compact=w<430,joyX=Math.max(72,insets.left+(compact?72:88)),y=h-Math.max(76,insets.bottom+(compact?76:90)),actionX=w-Math.max(64,insets.right+(compact?64:78)),dashX=actionX-(compact?84:90);scene.ahJoyBase.setPosition(joyX,y);scene.ahJoyHit.setPosition(joyX,y);if(scene.ahJoyPointer===null)scene.ahJoyThumb.setPosition(joyX,y);scene.ahActionRing.setPosition(actionX,y);scene.ahActionLabel.setPosition(actionX,y);scene.ahActionHit.setPosition(actionX,y);scene.ahRestoreRing.setPosition(actionX,y);scene.ahRestoreLabel.setPosition(actionX,y);scene.ahRestoreHit.setPosition(actionX,y);scene.ahDashRing.setPosition(dashX,y+4);scene.ahDashLabel.setPosition(dashX,y+4);scene.ahDashHit.setPosition(dashX,y+4);scene.ahPrompt.setPosition(w/2,Math.max(12,insets.top+12));scene.ahMessage.setPosition(w/2,Math.max(52,insets.top+52));if(scene.ahCombatHud){scene.ahCombatHud.enemyLabel.setX(w-16);updateCombatHUD(scene);} }
  function updateJoy(scene,p){let x=p.x-scene.ahJoyBase.x,y=p.y-scene.ahJoyBase.y,d=Math.hypot(x,y);if(d>48){x*=48/d;y*=48/d;}scene.ahJoyThumb.setPosition(scene.ahJoyBase.x+x,scene.ahJoyBase.y+y);if(d<11){scene.ahJoy.x=scene.ahJoy.y=0;return;}d=Math.hypot(x,y)||1;scene.ahJoy.x=x/d;scene.ahJoy.y=y/d;}
  function resetJoy(scene){scene.ahJoyPointer=null;scene.ahJoy.x=scene.ahJoy.y=0;scene.ahJoyThumb?.setPosition(scene.ahJoyBase.x,scene.ahJoyBase.y);}
  function later(scene,delay,callback){const event=scene.time.delayedCall(delay,()=>{scene.ahTimers?.delete(event);callback();});scene.ahTimers?.add(event);return event;}
  function clearTimers(scene){scene.ahTimers?.forEach(event=>event.remove?.(false));scene.ahTimers?.clear?.();}
  function clearCombatTransient(scene){scene.ahAttackSlash?.destroy?.();scene.ahAttackSlash=null;scene.ahTelegraph?.destroy?.();scene.ahTelegraph=null;scene.ahNodePulse?.destroy?.();scene.ahNodePulse=null;scene.ahDashTrail?.forEach?.(trail=>trail.destroy?.());scene.ahDashTrail=[];}
  function buildCombatHUD(scene){if(scene.ahCombatHud)return;const graphics=scene.add.graphics().setScrollFactor(0).setDepth(150);const playerLabel=scene.add.text(16,14,"ALPHA",{fontFamily:"system-ui",fontSize:"11px",color:"#dff8ff",fontStyle:"bold"}).setScrollFactor(0).setDepth(151);const enemyLabel=scene.add.text(scene.scale.width-16,14,"SENTINEL",{fontFamily:"system-ui",fontSize:"11px",color:"#ffc0cb",fontStyle:"bold"}).setOrigin(1,0).setScrollFactor(0).setDepth(151);scene.ahCombatHud={graphics,playerLabel,enemyLabel};updateCombatHUD(scene);}
  function updateCombatHUD(scene){const hud=scene.ahCombatHud;if(!hud)return;const g=hud.graphics,w=scene.scale.width;g.clear();for(let i=0;i<PLAYER_MAX_HP;i++){g.fillStyle(i<scene.ahPlayerHP?0x65e8ff:0x23343d,1);g.fillRoundedRect(16+i*34,32,27,10,3);}g.fillStyle(0x30111b,.92);g.fillRoundedRect(w-178,32,162,10,3);g.fillStyle(0xff607a,1);g.fillRoundedRect(w-178,32,162*(Math.max(0,scene.ahSentinelHP)/SENTINEL_MAX_HP),10,3);}
  function destroyCombatHUD(scene){const hud=scene.ahCombatHud;if(!hud)return;Object.values(hud).forEach(item=>item?.destroy?.());scene.ahCombatHud=null;}
  function setSentinelActive(scene,active){const s=scene.ahSentinel;if(!s)return;scene.ahSentinelActive=!!active;s.body.enable=!!active;s.setAlpha(active?1:.32);s.setFillStyle(active?0x8e263e:0x6a2337,active?1:.55);s.setStrokeStyle(3,active?0xff8295:0xff6b86,active?1:.8);scene.ahSentinelFallbackGlow?.setVisible(!scene.ahSentinelVisual).setAlpha(active ? .22 : .12);setSentinelVisual(scene,active?"idle":"dormant");if(!active)s.body.setVelocity(0,0);syncSentinelVisual(scene);}
  function resetSentinel(scene){const s=scene.ahSentinel;if(!s)return;s.setPosition(scene.ahSentinelSpawn.x,scene.ahSentinelSpawn.y);s.body.reset(s.x,s.y);s.body.setVelocity(0,0);scene.ahSentinelHP=SENTINEL_MAX_HP;scene.ahSentinelState="idle";scene.ahSentinelStateUntil=scene.time.now+800;scene.ahSentinelHitThisLunge=false;setSentinelActive(scene,true);setSentinelVisual(scene,"idle");}
  function startEncounter(scene){if(scene.ahCombatState!=="precombat"||scene.ahEncounterStarted)return;scene.ahEncounterStarted=true;scene.ahCombatState="active";scene.ahPlayerControl=true;setBarrier(scene,true);resetSentinel(scene);buildCombatHUD(scene);setContext(scene,"combat");showMessage(scene,"CORRUPTED RELAY SENTINEL");}
  function endVictory(scene){if(scene.ahCombatState!=="active")return;scene.ahCombatState="victory";scene.ahSignalAccessRestored=true;scene.ahSignalRestored=false;setNodeState(scene,"available");scene.events.emit("relay-node-available",{sectorId:SECTOR_ID});scene.ahSentinelState="defeated";scene.ahSentinel?.body?.setVelocity(0,0);scene.ahSentinel?.body&&(scene.ahSentinel.body.enable=false);scene.ahSentinel?.setFillStyle(0x1d3540,.9);scene.ahSentinel?.setStrokeStyle(3,0x8fd5e0,.8);setSentinelVisual(scene,"defeated");clearCombatTransient(scene);setBarrier(scene,false);destroyCombatHUD(scene);setContext(scene,null);showMessage(scene,"GUARDIAN DISABLED\nRELAY NODE AVAILABLE");}
  function removeDefeatOverlay(scene){scene.ahDefeatOverlay?.forEach?.(item=>item.destroy?.());scene.ahDefeatOverlay=null;}
  function leaveSector(scene){if(scene.ahCombatState==="cleanup")return;scene.ahCombatState="cleanup";scene.ahPlayerControl=false;void close();}
  function resetEncounter(scene){removeDefeatOverlay(scene);clearTimers(scene);clearCombatTransient(scene);scene.ahMessage?.setVisible(false);scene.ahPlayerHP=PLAYER_MAX_HP;scene.ahNextAttackAt=0;scene.ahNextDashAt=0;scene.ahDashUntil=0;scene.ahPlayerControl=true;scene.ahCombatState="precombat";scene.ahEncounterStarted=false;scene.ahSignalAccessRestored=false;scene.ahSignalRestored=false;setNodeState(scene,"locked");scene.ahSentinelHP=SENTINEL_MAX_HP;scene.ahPlayer?.setPosition(ARENA.triggerX+56,ARENA.triggerY);scene.ahPlayer?.body?.reset(scene.ahPlayer.x,scene.ahPlayer.y);setBarrier(scene,false);startEncounter(scene);}
  function showDefeatOverlay(scene){removeDefeatOverlay(scene);const w=scene.scale.width,h=scene.scale.height,items=[],add=item=>{items.push(item);return item;};add(scene.add.rectangle(w/2,h/2,w,h,0x03070b,.74).setScrollFactor(0).setDepth(180));add(scene.add.text(w/2,h/2-92,"SIGNAL LOST",{fontFamily:"system-ui",fontSize:"26px",color:"#ff8c9d",fontStyle:"bold"}).setOrigin(.5).setScrollFactor(0).setDepth(181));const retry=add(scene.add.rectangle(w/2,h/2-18,210,48,0x174755,.94).setStrokeStyle(2,0x8ff5ff,.9).setScrollFactor(0).setDepth(181).setInteractive({useHandCursor:true}));add(scene.add.text(w/2,h/2-18,"RETRY",{fontFamily:"system-ui",fontSize:"14px",color:"#e5fdff",fontStyle:"bold"}).setOrigin(.5).setScrollFactor(0).setDepth(182));const leave=add(scene.add.rectangle(w/2,h/2+48,210,42,0x2c2028,.94).setStrokeStyle(2,0xff9aae,.8).setScrollFactor(0).setDepth(181).setInteractive({useHandCursor:true}));add(scene.add.text(w/2,h/2+48,"LEAVE SECTOR",{fontFamily:"system-ui",fontSize:"13px",color:"#ffe7ec",fontStyle:"bold"}).setOrigin(.5).setScrollFactor(0).setDepth(182));retry.on("pointerdown",()=>resetEncounter(scene));leave.on("pointerdown",()=>leaveSector(scene));scene.ahDefeatOverlay=items;}
  function endDefeat(scene){if(scene.ahCombatState!=="active")return;scene.ahCombatState="defeat";scene.ahPlayerControl=false;scene.ahSentinelState="stopped";scene.ahSentinel?.body?.setVelocity(0,0);clearCombatTransient(scene);destroyCombatHUD(scene);setContext(scene,null);later(scene,120,()=>showDefeatOverlay(scene));}
  function directionVector(scene){const v=scene.ahMove.clone();if(v.lengthSq()>0)return v.normalize();return ({left:{x:-1,y:0},right:{x:1,y:0},up:{x:0,y:-1},down:{x:0,y:1}})[scene.ahDirection]||{x:1,y:0};}
  function setPlayerVelocity(scene,x,y){const player=scene.ahPlayer;if(player?.setVelocity)player.setVelocity(x,y);else player?.body?.setVelocity?.(x,y);}
  function playerAttack(scene){const now=scene.time.now,p=scene.ahPlayer;if(scene.ahCombatState!=="active"||!p||now<scene.ahNextAttackAt)return;scene.ahNextAttackAt=now+ATTACK_COOLDOWN_MS;const v=directionVector(scene),hitX=p.x+v.x*MELEE_OFFSET,hitY=p.y+v.y*MELEE_OFFSET,slash=scene.add.circle(hitX,hitY,MELEE_RADIUS,0x9ff7ff,.28).setStrokeStyle(3,0xdffcff,.9).setDepth(40);scene.ahAttackSlash=slash;scene.tweens.add({targets:slash,scale:1.35,alpha:0,duration:150,onComplete:()=>slash.destroy()});later(scene,170,()=>{if(scene.ahAttackSlash===slash)scene.ahAttackSlash=null;});const s=scene.ahSentinel;if(s&&scene.ahSentinelActive&&global.Phaser.Math.Distance.Between(hitX,hitY,s.x,s.y)<=MELEE_RADIUS+SENTINEL_HIT_RADIUS){scene.ahSentinelHP=Math.max(0,scene.ahSentinelHP-1);s.setFillStyle(0xffe0e5,1);later(scene,90,()=>scene.ahSentinelActive&&s.setFillStyle(0x8e263e,1));updateCombatHUD(scene);if(scene.ahSentinelHP===0)endVictory(scene);}}
  function playerDash(scene){const now=scene.time.now,p=scene.ahPlayer;if(!scene.ahPlayerControl||!p||now<scene.ahNextDashAt)return;scene.ahNextDashAt=now+DASH_COOLDOWN_MS;scene.ahDashUntil=now+DASH_DURATION_MS;const v=directionVector(scene),trail=scene.add.circle(p.x,p.y,25,0x65e8ff,.32).setDepth(26);scene.ahDashTrail=(scene.ahDashTrail||[]).concat(trail);scene.tweens.add({targets:trail,scale:2.2,alpha:0,duration:DASH_DURATION_MS,onComplete:()=>trail.destroy()});setPlayerVelocity(scene,v.x*DASH_SPEED,v.y*DASH_SPEED);}
  function sentinelTelegraph(scene,now){const s=scene.ahSentinel;if(!s)return;scene.ahSentinelState="telegraph";scene.ahSentinelStateUntil=now+700;s.body.setVelocity(0,0);setSentinelVisual(scene,"telegraph");const ring=scene.add.circle(s.x,s.y,46,0xff5471,.13).setStrokeStyle(3,0xff738c,.95).setDepth(24);scene.ahTelegraph=ring;scene.tweens.add({targets:ring,scale:2.05,alpha:.72,duration:680});}
  function sentinelLunge(scene,now){const s=scene.ahSentinel,p=scene.ahPlayer;if(!s||!p)return;scene.ahTelegraph?.destroy?.();scene.ahTelegraph=null;const v=new global.Phaser.Math.Vector2(p.x-s.x,p.y-s.y);if(v.lengthSq()<1)v.setTo(1,0);v.normalize();scene.ahSentinelLunge={x:v.x,y:v.y};scene.ahSentinelState="lunge";scene.ahSentinelStateUntil=now+440;scene.ahSentinelHitThisLunge=false;s.setFillStyle(0xff5877,1);setSentinelVisual(scene,"lunge");s.body.setVelocity(v.x*430,v.y*430);}
  function damagePlayer(scene){if(scene.ahCombatState!=="active")return;scene.ahPlayerHP=Math.max(0,scene.ahPlayerHP-1);scene.ahPlayer?.setTint?.(0xff8ca0);later(scene,100,()=>scene.ahPlayer?.clearTint?.());updateCombatHUD(scene);if(scene.ahPlayerHP===0)endDefeat(scene);}
  function updateSentinel(scene,now){if(scene.ahCombatState!=="active"||!scene.ahSentinelActive)return;const s=scene.ahSentinel,p=scene.ahPlayer,state=scene.ahSentinelState;if(!s||!p)return;if(state==="idle"){const v=new global.Phaser.Math.Vector2(p.x-s.x,p.y-s.y);if(v.lengthSq()>70*70){v.normalize();s.body.setVelocity(v.x*42,v.y*42);}else s.body.setVelocity(0,0);if(now>=scene.ahSentinelStateUntil)sentinelTelegraph(scene,now);syncSentinelVisual(scene);return;}if(state==="telegraph"){if(now>=scene.ahSentinelStateUntil)sentinelLunge(scene,now);syncSentinelVisual(scene);return;}if(state==="lunge"){if(!scene.ahSentinelHitThisLunge&&global.Phaser.Math.Distance.Between(s.x,s.y,p.x,p.y)<76){scene.ahSentinelHitThisLunge=true;damagePlayer(scene);}if(now>=scene.ahSentinelStateUntil){s.body.setVelocity(0,0);s.setFillStyle(0x8e263e,1);setSentinelVisual(scene,"idle");scene.ahSentinelState="recovery";scene.ahSentinelStateUntil=now+900;}syncSentinelVisual(scene);return;}if(state==="recovery"&&now>=scene.ahSentinelStateUntil){scene.ahSentinelState="idle";scene.ahSentinelStateUntil=now+350;}syncSentinelVisual(scene);}
  function setContext(scene,context){if(scene.ahContext===context)return;scene.ahContext=context;const active=!!context;scene.ahActionRing.setVisible(active);scene.ahActionLabel.setVisible(active);scene.ahActionHit.setVisible(active);if(context==="node"){scene.ahActionLabel.setText("RESTORE\nSIGNAL");scene.ahPrompt.setText(scene.ahTouch?"DEAD RELAY NODE IN RANGE":"DEAD RELAY NODE IN RANGE · E / SPACE");}else if(context==="exit"){scene.ahActionLabel.setText("EXIT");scene.ahPrompt.setText(scene.ahTouch?"EXIT TO MAP":"EXIT TO MAP · E / SPACE");}else scene.ahPrompt.setText(scene.ahTouch?"":"WASD / ARROWS · MOVE");}
  function showMessage(scene,text){scene.ahMessageTimer?.remove?.(false);scene.ahMessage.setText(text).setVisible(true);scene.ahMessageTimer=scene.time.delayedCall(1500,()=>scene.ahMessage?.setVisible(false));}
  function perform(scene){if(scene.ahContext==="exit"){void close();return;}if(scene.ahContext!=="node"||scene.ahNodeRestored)return;scene.ahNodeRestored=true;showMessage(scene,"SIGNAL FOUND · ROUTE STABLE");const node=scene.ahNode;node?.setTint?.(0xbffaff);scene.tweens.add({targets:node,scaleX:(node?.scaleX||1)*1.04,scaleY:(node?.scaleY||1)*1.04,duration:120,yoyo:true,onComplete:()=>{node?.clearTint?.();}});const pulse=scene.add.circle(scene.ahNodeAnchor.x,scene.ahNodeAnchor.y,34,0x65e8ff,.52).setDepth(25);scene.tweens.add({targets:pulse,scale:3,alpha:0,duration:520,onComplete:()=>pulse.destroy()});}
  function createKeyboard(scene){if(!scene.input.keyboard)return;scene.ahCursors=scene.input.keyboard.createCursorKeys();scene.ahKeys=scene.input.keyboard.addKeys({up:global.Phaser.Input.Keyboard.KeyCodes.W,left:global.Phaser.Input.Keyboard.KeyCodes.A,down:global.Phaser.Input.Keyboard.KeyCodes.S,right:global.Phaser.Input.Keyboard.KeyCodes.D,interact:global.Phaser.Input.Keyboard.KeyCodes.E,space:global.Phaser.Input.Keyboard.KeyCodes.SPACE,escape:global.Phaser.Input.Keyboard.KeyCodes.ESC});}
  function updatePlayer(scene){let x=scene.ahJoy.x,y=scene.ahJoy.y,k=scene.ahKeys,c=scene.ahCursors;if(k?.left?.isDown||c?.left?.isDown)x--;if(k?.right?.isDown||c?.right?.isDown)x++;if(k?.up?.isDown||c?.up?.isDown)y--;if(k?.down?.isDown||c?.down?.isDown)y++;const move=scene.ahMove.set(x,y);if(move.lengthSq()>0){move.normalize().scale(PLAYER_SPEED);scene.ahPlayer.setVelocity(move.x,move.y);setAnimation(scene,Math.abs(move.x)>Math.abs(move.y)?(move.x<0?"left":"right"):(move.y<0?"up":"down"),true);}else{scene.ahPlayer.setVelocity(0,0);setAnimation(scene,scene.ahDirection,false);}}
  function proximity(scene){const p=scene.ahPlayer,n=scene.ahNodeAnchor,e=scene.ahExit,dist=global.Phaser.Math.Distance.Squared;const options=[];if(n&&dist(p.x,p.y,n.x,n.y)<=NODE_RANGE_SQ)options.push({context:"node",d:dist(p.x,p.y,n.x,n.y)});if(e&&dist(p.x,p.y,e.x,e.y)<=EXIT_RANGE_SQ)options.push({context:"exit",d:dist(p.x,p.y,e.x,e.y)});options.sort((a,b)=>a.d-b.d);setContext(scene,options[0]?.context||null);}
  function shutdown(){const scene=this;resetJoy(scene);scene.ahStop?.();scene.ahJoyHit?.removeAllListeners();scene.ahActionHit?.removeAllListeners();scene.input?.off("pointermove",scene.ahOnMove);scene.input?.off("pointerup",scene.ahOnUp);scene.ahMessageTimer?.remove?.(false);}
  function setContext(scene,context){if(scene.ahContext===context)return;scene.ahContext=context;const active=context==="combat"||context==="exit";scene.ahActionRing.setVisible(active);scene.ahActionLabel.setVisible(active);scene.ahActionHit.setVisible(active);if(context==="combat"){scene.ahActionLabel.setText("STRIKE");scene.ahPrompt.setText(scene.ahTouch?"STRIKE":"SPACE / CLICK · STRIKE · SHIFT DASH");}else if(context==="node_locked"){scene.ahPrompt.setText("DEAD RELAY NODE · GUARDIAN LOCK");}else if(context==="signal_ready"){scene.ahPrompt.setText("SIGNAL ACCESS RESTORED");}else if(context==="exit"){scene.ahActionLabel.setText("EXIT");scene.ahPrompt.setText(scene.ahTouch?"EXIT TO MAP":"EXIT TO MAP · E");}else scene.ahPrompt.setText(scene.ahTouch?"":"WASD / ARROWS · MOVE");}
  function showMessage(scene,text){scene.ahMessageTimer?.remove?.(false);scene.ahMessage.setText(text).setVisible(true);scene.ahMessageTimer=later(scene,1500,()=>scene.ahMessage?.setVisible(false));}
  function perform(scene){if(scene.ahCombatState==="active"){playerAttack(scene);return;}if(scene.ahContext==="exit")leaveSector(scene);}
  function createKeyboard(scene){if(!scene.input.keyboard)return;scene.ahCursors=scene.input.keyboard.createCursorKeys();scene.ahKeys=scene.input.keyboard.addKeys({up:global.Phaser.Input.Keyboard.KeyCodes.W,left:global.Phaser.Input.Keyboard.KeyCodes.A,down:global.Phaser.Input.Keyboard.KeyCodes.S,right:global.Phaser.Input.Keyboard.KeyCodes.D,interact:global.Phaser.Input.Keyboard.KeyCodes.E,space:global.Phaser.Input.Keyboard.KeyCodes.SPACE,dash:global.Phaser.Input.Keyboard.KeyCodes.SHIFT,escape:global.Phaser.Input.Keyboard.KeyCodes.ESC});}
  function updatePlayer(scene){if(!scene.ahPlayerControl){scene.ahStop?.();return;}const now=scene.time.now;if(now<scene.ahDashUntil)return;let x=scene.ahJoy.x,y=scene.ahJoy.y,k=scene.ahKeys,c=scene.ahCursors;if(k?.left?.isDown||c?.left?.isDown)x--;if(k?.right?.isDown||c?.right?.isDown)x++;if(k?.up?.isDown||c?.up?.isDown)y--;if(k?.down?.isDown||c?.down?.isDown)y++;const move=scene.ahMove.set(x,y);if(move.lengthSq()>0){move.normalize().scale(PLAYER_SPEED);setPlayerVelocity(scene,move.x,move.y);setAnimation(scene,Math.abs(move.x)>Math.abs(move.y)?(move.x<0?"left":"right"):(move.y<0?"up":"down"),true);}else{setPlayerVelocity(scene,0,0);setAnimation(scene,scene.ahDirection,false);}}
  function proximity(scene){if(scene.ahCombatState==="active"){setContext(scene,"combat");return;}const p=scene.ahPlayer,n=scene.ahNodeAnchor,e=scene.ahExit,dist=global.Phaser.Math.Distance.Squared;const options=[];if(n&&dist(p.x,p.y,n.x,n.y)<=NODE_RANGE_SQ)options.push({context:scene.ahSignalAccessRestored?"signal_ready":"node_locked",d:dist(p.x,p.y,n.x,n.y)});if(e&&dist(p.x,p.y,e.x,e.y)<=EXIT_RANGE_SQ)options.push({context:"exit",d:dist(p.x,p.y,e.x,e.y)});options.sort((a,b)=>a.d-b.d);setContext(scene,options[0]?.context||null);}
  function shutdown(){const scene=this;scene.ahResetInput?.();scene.ahStop?.();clearTimers(scene);clearCombatTransient(scene);destroyCombatHUD(scene);removeDefeatOverlay(scene);scene.ahJoyHit?.off("pointerdown",scene.ahOnJoyDown);scene.ahActionHit?.off("pointerdown",scene.ahOnAttackDown);scene.ahDashHit?.off("pointerdown",scene.ahOnDashDown);scene.ahRestoreHit?.off("pointerdown",scene.ahOnRestoreDown);scene.input?.off("pointermove",scene.ahOnMove);scene.input?.off("pointerup",scene.ahOnUp);scene.input?.off("gameout",scene.ahOnGameOut);scene.input?.off("pointerdown",scene.ahOnCombatPointer);scene.ahMessageTimer?.remove?.(false);}
  function setContext(scene,context){if(scene.ahContext===context)return;scene.ahContext=context;const combat=context==="combat",active=combat||context==="exit";scene.ahActionRing.setVisible(active);scene.ahActionLabel.setVisible(active);scene.ahActionHit.setVisible(active);scene.ahDashRing.setVisible(combat);scene.ahDashLabel.setVisible(combat);scene.ahDashHit.setVisible(combat);if(combat){scene.ahActionLabel.setText("STRIKE");scene.ahPrompt.setText(scene.ahTouch?"STRIKE + DASH":"SPACE / CLICK · STRIKE · SHIFT DASH");}else if(context==="node_locked"){scene.ahPrompt.setText("DEAD RELAY NODE · GUARDIAN LOCK");}else if(context==="signal_ready"){scene.ahPrompt.setText("SIGNAL ACCESS RESTORED");}else if(context==="exit"){scene.ahActionLabel.setText("EXIT");scene.ahPrompt.setText(scene.ahTouch?"EXIT TO MAP":"EXIT TO MAP · E");}else scene.ahPrompt.setText(scene.ahTouch?"":"WASD / ARROWS · MOVE");}
  function setContext(scene,context){if(scene.ahContext===context)return;scene.ahContext=context;const combat=context==="combat",restore=context==="node_available",active=combat||restore||context==="exit";scene.ahActionRing.setVisible(active);scene.ahActionLabel.setVisible(active);scene.ahActionHit.setVisible(active);scene.ahDashRing.setVisible(combat);scene.ahDashLabel.setVisible(combat);scene.ahDashHit.setVisible(combat);if(combat){scene.ahActionLabel.setText("STRIKE");scene.ahPrompt.setText(scene.ahTouch?"STRIKE + DASH":"SPACE / CLICK · STRIKE · SHIFT DASH");}else if(restore){scene.ahActionLabel.setText("RESTORE");scene.ahPrompt.setText(scene.ahTouch?"RELAY NODE READY":"RELAY NODE READY · E");}else if(context==="exit"){scene.ahActionLabel.setText("EXIT");scene.ahPrompt.setText(scene.ahTouch?"EXIT TO MAP":"EXIT TO MAP · E");}else scene.ahPrompt.setText(scene.ahTouch?"":"WASD / ARROWS · MOVE");}
  function setContext(scene,context){if(scene.ahContext===context)return;scene.ahContext=context;const combat=context==="combat",restore=context==="node_available",restoreMobile=restore&&scene.ahTouch,active=combat||context==="exit";scene.ahActionRing.setVisible(active);scene.ahActionLabel.setVisible(active);scene.ahActionHit.setVisible(active);scene.ahRestoreRing.setVisible(restoreMobile);scene.ahRestoreLabel.setVisible(restoreMobile);scene.ahRestoreHit.setVisible(restoreMobile);scene.ahDashRing.setVisible(combat);scene.ahDashLabel.setVisible(combat);scene.ahDashHit.setVisible(combat);if(combat){scene.ahActionLabel.setText("STRIKE");scene.ahPrompt.setText(scene.ahTouch?"STRIKE + DASH":"SPACE / CLICK · STRIKE · SHIFT DASH");}else if(restore){scene.ahPrompt.setText(scene.ahTouch?"RELAY NODE READY":"RELAY NODE READY · E");}else if(context==="exit"){scene.ahActionLabel.setText("EXIT");scene.ahPrompt.setText(scene.ahTouch?"EXIT TO MAP":"EXIT TO MAP · E");}else scene.ahPrompt.setText(scene.ahTouch?"":"WASD / ARROWS · MOVE");}
  function setContext(scene,context){if(scene.ahContext===context)return;scene.ahContext=context;const combat=context==="combat",restore=context==="node_available",restoreMobile=restore&&scene.ahTouch,action=combat||context==="exit";scene.ahActionRing.setVisible(action);scene.ahActionLabel.setVisible(action);scene.ahActionHit.setVisible(action);scene.ahActionHit.input.enabled=action;scene.ahRestoreRing.setVisible(restoreMobile);scene.ahRestoreLabel.setVisible(restoreMobile);scene.ahRestoreHit.setVisible(restoreMobile);scene.ahRestoreHit.input.enabled=restoreMobile;scene.ahDashRing.setVisible(combat);scene.ahDashLabel.setVisible(combat);scene.ahDashHit.setVisible(combat);scene.ahDashHit.input.enabled=combat;if(combat){scene.ahActionLabel.setText("STRIKE");scene.ahPrompt.setText(scene.ahTouch?"STRIKE + DASH":"SPACE / CLICK · STRIKE · SHIFT DASH");}else if(restore){scene.ahPrompt.setText(scene.ahTouch?"RELAY NODE READY":"RELAY NODE READY · E");}else if(context==="exit"){scene.ahActionLabel.setText("EXIT");scene.ahPrompt.setText(scene.ahTouch?"EXIT TO MAP":"EXIT TO MAP · E");}else scene.ahPrompt.setText(scene.ahTouch?"":"WASD / ARROWS · MOVE");}
  function perform(scene){if(scene.ahCombatState==="active"){playerAttack(scene);return;}if(scene.ahContext==="node_available"){restoreSignal(scene);return;}if(scene.ahContext==="exit")leaveSector(scene);}
  function proximity(scene){if(scene.ahCombatState==="active"){setContext(scene,"combat");return;}const p=scene.ahPlayer,n=scene.ahNodeAnchor,e=scene.ahExit,dist=global.Phaser.Math.Distance.Squared;const options=[];if(scene.ahNodeState==="available"&&n&&dist(p.x,p.y,n.x,n.y)<=RELAY_NODE_RANGE_SQ)options.push({context:"node_available",d:dist(p.x,p.y,n.x,n.y)});if(e&&dist(p.x,p.y,e.x,e.y)<=EXIT_RANGE_SQ)options.push({context:"exit",d:dist(p.x,p.y,e.x,e.y)});options.sort((a,b)=>a.d-b.d);setContext(scene,options[0]?.context||null);}
  function roomError(stage,error){const failure=error instanceof Error?error:new Error(String(error||stage));failure.relayStage=stage;return failure;}
  function preload(){trace("SCENE_PRELOAD");this.ahLoadErrors=new Set();this.load.on("loaderror",file=>{this.ahLoadErrors.add(file?.key);log("asset fallback",file?.key);});const simulated=global.__AH_EXPLORATION_SIMULATE_MISSING_ASSET;Object.values(ASSETS).forEach(asset=>{if(simulated===asset.key)return;this.load.image(asset.key,asset.url);});if(simulated!==PLAYER_SHEET)this.load.spritesheet(PLAYER_SHEET,PLAYER_SHEET_URL,{frameWidth:256,frameHeight:256});}
  function create(){try{trace("SCENE_CREATE_START");this.physics.world.setBounds(0,0,WORLD_WIDTH,WORLD_HEIGHT);buildWorld(this);trace("PLAYER_CREATED");createControls(this);createKeyboard(this);trace("INPUT_READY");this.cameras.main.setBounds(0,0,WORLD_WIDTH,WORLD_HEIGHT);this.cameras.main.startFollow(this.ahPlayer,true,.13,.13);this.cameras.main.setRoundPixels(true);this.sys.events.once("shutdown",shutdown,this);S.scene=this;S.canvas=S.canvasParent?.querySelector("canvas")||this.game.canvas;if(!S.canvas||!this.ahPlayer||!this.input)throw roomError("SCENE CREATE FAILED",new Error("Relay scene readiness is incomplete"));trace("CANVAS_READY");S.canvas.setAttribute("aria-label","Relay Fringe 01 playable signal approach");S.canvas.addEventListener("pointercancel",resetPointer);onResize();this.events.emit("relay-room-ready",{canvas:S.canvas,player:this.ahPlayer});trace("ROOM_READY");settle(true);}catch(error){settle(false,roomError("SCENE CREATE FAILED",error));}}
  function update(){if(S.closing||this.ahPaused||!this.ahPlayer)return;updatePlayer(this);if(this.ahCombatState==="precombat"&&!this.ahEncounterStarted&&global.Phaser.Geom.Rectangle.Contains(this.ahTrigger.getBounds(),this.ahPlayer.x,this.ahPlayer.y))startEncounter(this);updateSentinel(this,this.time.now);proximity(this);const k=this.ahKeys;if(global.Phaser.Input.Keyboard.JustDown(k?.interact))perform(this);if(global.Phaser.Input.Keyboard.JustDown(k?.space))playerAttack(this);if(global.Phaser.Input.Keyboard.JustDown(k?.dash))playerDash(this);if(global.Phaser.Input.Keyboard.JustDown(k?.escape))leaveSector(this);}
  function settle(ok,error){const resolve=S.resolveReady,reject=S.rejectReady;S.resolveReady=S.rejectReady=null;if(S.readyTimer){clearTimeout(S.readyTimer);S.readyTimer=null;}if(ok)resolve?.(true);else reject?.(error||new Error("Room unavailable"));}
  function nextFrame(){return new Promise(resolve=>{if(typeof global.requestAnimationFrame!=="function")return resolve();global.requestAnimationFrame(()=>resolve());});}
  function elementFacts(element){const style=element?.isConnected?getComputedStyle(element):null,rect=element?.getBoundingClientRect?.(),parent=element?.parentElement,parentStyle=parent?.isConnected?getComputedStyle(parent):null;return {connected:!!element?.isConnected,rect:{left:Math.round(rect?.left||0),top:Math.round(rect?.top||0),width:Math.round(rect?.width||0),height:Math.round(rect?.height||0)},display:style?.display||"missing",visibility:style?.visibility||"missing",opacity:Number(style?.opacity||0),zIndex:style?.zIndex||"auto",position:style?.position||"missing",pointerEvents:style?.pointerEvents||"missing",hidden:!!element?.hidden,parentConnected:!!parent?.isConnected,parentDisplay:parentStyle?.display||"missing",parentVisibility:parentStyle?.visibility||"missing"};}
  function rectIntersectsViewport(rect){return !!rect&&rect.width>0&&rect.height>0&&rect.right>0&&rect.bottom>0&&rect.left<global.innerWidth&&rect.top<global.innerHeight;}
  function controlFacts(){const scene=S.scene,canvasRect=S.canvas?.getBoundingClientRect?.(),scaleW=scene?.scale?.width||1,scaleH=scene?.scale?.height||1;return ["ahJoyHit","ahActionHit","ahDashHit"].map(name=>{const control=scene?.[name],left=(canvasRect?.left||0)+((control?.x||0)/scaleW)*(canvasRect?.width||0),top=(canvasRect?.top||0)+((control?.y||0)/scaleH)*(canvasRect?.height||0);return {name,exists:!!control,visible:control?.visible===true,pointerEnabled:control?.input?.enabled===true,viewportIntersect:!!control&&left>=0&&top>=0&&left<global.innerWidth&&top<global.innerHeight};});}
  function postReadyFacts(){const canvasRect=S.canvas?.getBoundingClientRect?.(),centerX=Math.max(0,Math.min(global.innerWidth-1,Math.round((canvasRect?.left||0)+(canvasRect?.width||0)/2))),centerY=Math.max(0,Math.min(global.innerHeight-1,Math.round((canvasRect?.top||0)+(canvasRect?.height||0)/2))),top=document.elementFromPoint?.(centerX,centerY)||null,loading=elementFacts(S.loading),canvas=elementFacts(S.canvas),root=elementFacts(S.root),map=elementFacts(document.getElementById("mapBack")),panel=elementFacts(document.getElementById("worldExplorationPanel")),backdrop=elementFacts(document.querySelector("#worldExplorationPanel .world-exploration-backdrop"));return {canvas,root,loading,map,panel,backdrop,canvasCount:document.querySelectorAll("#"+ROOT_ID+" canvas").length,mobileControlRoots:controlFacts(),topmost:{tag:top?.tagName||"",id:top?.id||"",className:String(top?.className||"").slice(0,120),isCanvas:top===S.canvas},viewport:{width:global.innerWidth,height:global.innerHeight},canvasIntersectsViewport:rectIntersectsViewport(canvasRect)};}
  function presentationFailure(facts){if(!facts.canvas.connected)return "canvas_disconnected";if(!(facts.canvas.rect.width>0&&facts.canvas.rect.height>0))return "canvas_zero_size";if(facts.canvas.display==="none")return "canvas_display_none";if(facts.canvas.visibility==="hidden")return "canvas_visibility_hidden";if(!(facts.canvas.opacity>0))return "canvas_opacity_zero";if(!facts.canvasIntersectsViewport)return "canvas_outside_viewport";if(facts.root.display==="none"||facts.root.visibility==="hidden"||!(facts.root.opacity>0))return "gameplay_root_not_visible";if(facts.root.pointerEvents==="none")return "gameplay_root_pointer_events_none";if(facts.loading.connected&&facts.loading.display!=="none"&&!facts.loading.hidden)return "loading_layer_still_visible";if(!facts.topmost.isCanvas)return "canvas_center_covered_by_"+(facts.topmost.id||facts.topmost.className||facts.topmost.tag||"unknown");return "";}
  function showPostReadyDiagnostic(facts){if(!S.devPreview)return;S.root?.querySelector(".ah-exploration-room__diagnostic")?.remove();const badge=document.createElement("div");badge.className="ah-exploration-room__diagnostic";badge.textContent=`READY · canvas ${facts.canvas.rect.width}x${facts.canvas.rect.height} · loading ${facts.loading.display} · canvases ${facts.canvasCount} · controls ${facts.mobileControlRoots.length} · top ${facts.topmost.tag||"none"}`;S.root?.appendChild(badge);if(S.diagnosticTimer)clearTimeout(S.diagnosticTimer);S.diagnosticTimer=setTimeout(()=>badge.remove(),2600);}
  async function revealAfterReady(){S.root.style.display="grid";S.root.style.visibility="visible";S.root.style.opacity="1";S.root.style.pointerEvents="auto";S.canvas.style.display="block";S.canvas.style.visibility="visible";S.canvas.style.opacity="1";if(S.dbg&&global.__AH_EXPLORATION_SIMULATE_FALSE_READY_LOADING===true){S.loading.hidden=false;S.loading.style.display="grid";}S.loading.hidden=true;S.loading.style.display="none";S.loading.style.pointerEvents="none";if(S.devPreview&&global.__AH_EXPLORATION_SIMULATE_HIDDEN_CANVAS===true)S.canvas.style.visibility="hidden";await nextFrame();const facts=postReadyFacts(),failed=presentationFailure(facts);if(S.devPreview){global.__AH_EXPLORATION_POST_READY_FACTS=facts;try{console.debug("[ExplorationRoom] post-ready presentation",facts);}catch(_){}}if(failed){const error=roomError("CANVAS_NOT_VISIBLE_AFTER_READY",new Error(failed));error.relayPresentationFacts=facts;throw error;}showPostReadyDiagnostic(facts);try{S.game?.canvas?.focus?.();if(S.game?.input)S.game.input.enabled=true;if(S.scene?.input)S.scene.input.enabled=true;}catch(_){}return facts;}
  function waitForLayout(){return new Promise(resolve=>{let frames=0;const next=()=>{frames+=1;if(frames>=2||typeof global.requestAnimationFrame!=="function")return resolve();global.requestAnimationFrame(next);};if(typeof global.requestAnimationFrame!=="function")return resolve();global.requestAnimationFrame(next);});}
  async function prepareGameMount(){if(!S.root?.isConnected||!S.canvasParent?.isConnected)throw roomError("MOUNT_HAS_ZERO_SIZE",new Error("Relay gameplay root is detached."));S.root.style.display="grid";S.root.style.pointerEvents="auto";try{S.tg?.expand?.();}catch(_){}await waitForLayout();const style=getComputedStyle(S.root),rect=S.canvasParent.getBoundingClientRect(),w=Math.round(rect.width),h=Math.round(rect.height);log("Phaser create mount",{hidden:document.hidden,visibility:document.visibilityState,display:style.display,pointerEvents:style.pointerEvents,width:w,height:h});if(style.display==="none"||style.pointerEvents==="none"||!(w>0&&h>0))throw roomError("MOUNT_HAS_ZERO_SIZE",new Error("Relay gameplay mount has no usable size."));}
  function createGame(){return new Promise((resolve,reject)=>{S.resolveReady=resolve;S.rejectReady=reject;S.readyTimer=setTimeout(()=>settle(false,roomError("CANVAS READY TIMEOUT",new Error("Relay room timed out"))),READY_TIMEOUT_MS);const w=S.canvasParent.clientWidth,h=S.canvasParent.clientHeight;try{trace("GAME_CREATED");S.game=new global.Phaser.Game({type:global.Phaser.AUTO,parent:CANVAS_ID,width:w,height:h,backgroundColor:"#071019",audio:{noAudio:true},input:{activePointers:4,touch:{capture:true}},scale:{mode:global.Phaser.Scale.RESIZE,width:w,height:h},physics:{default:"arcade",arcade:{gravity:{x:0,y:0},debug:!!global.DBG}},render:{roundPixels:true,powerPreference:"low-power"},scene:{preload,create,update}});}catch(error){settle(false,roomError("PHASER GAME CREATE FAILED",error));}});}
  async function cleanup(options){settle(false);if(S.diagnosticTimer){clearTimeout(S.diagnosticTimer);S.diagnosticTimer=null;}unbindEvents();const scene=S.scene;scene?.ahResetInput?.();scene?.ahStop?.();if(scene?.input)scene.input.enabled=false;const game=S.game;S.game=null;S.scene=null;if(game)try{game.destroy(true);}catch(error){log("destroy failed",error);}S.canvasParent?.replaceChildren();unregisterNavigation(!!options?.fromNavigation);S.root?.remove();S.root=S.canvasParent=S.loading=null;S.ready=false;restorePage();}
  async function runOpen(generation){try{injectCSS();buildShell();lockPage();readInsets();bindEvents();registerNavigation();if(!global.Phaser?.Game)throw roomError("PHASER LOAD FAILED",new Error("Phaser unavailable"));const delay=Math.max(0,Number(global.__AH_EXPLORATION_SIMULATE_OPEN_DELAY_MS)||0);if(S.dbg&&delay)await new Promise(resolve=>setTimeout(resolve,delay));if(S.dbg&&global.__AH_EXPLORATION_SIMULATE_UNRESOLVED_OPEN===true)await new Promise(()=>{});if(S.closing||generation!==S.generation)return false;await prepareGameMount();if(S.closing||generation!==S.generation)return false;const ready=await createGame();if(!ready||S.closing||generation!==S.generation)return false;if(!S.game||!S.scene?.ahPlayer||!S.scene?.input||!S.canvas)throw roomError("SCENE CREATE FAILED",new Error("Relay ready handshake failed"));await revealAfterReady();if(S.closing||generation!==S.generation)return false;S.ready=true;return true;}catch(error){const failure=roomError(error?.relayStage||"ROOM OPEN FAILED",error);log("open failed",failure);await cleanup();throw failure;}}
  function init(deps={}){S.tg=deps.tg||S.tg||global.Telegram?.WebApp||null;if(typeof deps.dbg==="boolean"||typeof deps.dbg==="function")S.dbg=deps.dbg;if(typeof deps.trace==="function")S.trace=deps.trace;S.devPreview=deps.devPreview===true;return API;}
  function open(options={}){if(String(options.sectorId||"")!==SECTOR_ID)return Promise.resolve(false);if(S.opening)return S.opening;if(isOpen()&&S.ready)return Promise.resolve(true);S.onClose=typeof options.onClose==="function"?options.onClose:null;S.closing=false;const generation=++S.generation;const task=runOpen(generation);let wrapped;wrapped=task.finally(()=>{if(S.opening===wrapped)S.opening=null;});S.opening=wrapped;return wrapped;}
  async function close(options){if(S.closing)return false;if(!S.root&&!S.game&&!S.opening)return false;S.closing=true;++S.generation;const after=S.onClose;S.onClose=null;try{await cleanup(options);await Promise.resolve(after?.());return true;}finally{S.closing=false;}}
  function isOpen(){return !!(S.root&&document.documentElement.contains(S.root)&&!S.closing);}
  const API={init,open,close,isOpen};global.AlphaExplorationRoom=API;
})(window);
