// Alpha Husky - Relay Fringe 01: Signal Approach.
// Local direct-control sector run. Progression submission is intentionally isolated from combat.
(function (global) {
  "use strict";

  const ROOT_ID = "alphaExplorationRoom";
  const CANVAS_ID = "alphaExplorationRoomCanvas";
  const STYLE_ID = "ah-exploration-room-css";
  const SECTOR = Object.freeze({
    sectorId: "relay_fringe_01",
    displayName: "Relay Fringe - Signal Approach",
    requiredEnemies: 5,
    enemyType: "corrupted_chaser",
    relayRequired: true,
    completionMode: "relay_activation"
  });
  // The previous Relay Fringe prototype remains available for later sector tuning.
  // It is deliberately dormant for the five-Chaser Signal Approach run.
  const LEGACY_RELAY_FEATURES = Object.freeze({ dash: false, sentinelEncounter: false });
  const WORLD = Object.freeze({ width: 1400, height: 900, playerSpawn: { x: 166, y: 700 }, relay: { x: 1010, y: 344 }, exit: { x: 1232, y: 692 } });
  const COMBAT = global.AlphaSectorCombatConfig?.makeCombatConfig?.({
    playerMaxHp: 100, playerDamage: 30, playerSpeed: 230, playerAttackRange: 86, playerAttackCooldownMs: 360,
    enemyMaxHp: 78, enemyDamage: 7, enemySpeed: 92, enemyAggroRange: 260, enemyAttackRange: 48, enemyAttackCooldownMs: 920
  }) || Object.freeze({ playerMaxHp: 100, playerDamage: 30, playerSpeed: 230, playerAttackRange: 86, playerAttackCooldownMs: 360, enemyMaxHp: 78, enemyDamage: 7, enemySpeed: 92, enemyAggroRange: 260, enemyAttackRange: 48, enemyAttackCooldownMs: 920 });
  const LOOT = Object.freeze({
    exp: { frame: 0, label: "EXP shard", value: 12, chance: 1 },
    scrap: { frame: 1, label: "Scrap", value: 1, chance: 0.60 },
    bones: { frame: 2, label: "Bones", value: 1, chance: 0.55 },
    equipment: { frame: 3, label: "Equipment drop", value: 1, chance: 0.20 }
  });
  const ENEMY_SPAWNS = Object.freeze([{ x: 476, y: 716 }, { x: 610, y: 512 }, { x: 824, y: 430 }, { x: 962, y: 610 }, { x: 1150, y: 420 }]);
  const ASSETS = Object.freeze({
    floor: { key: "ah-relay-floor", url: "assets/world_exploration/relay_fringe_01/relay_floor.webp" },
    relayIdle: { key: "ah-relay-node-idle", url: "assets/world_exploration/relay_fringe_01/dead_relay_node_idle.webp" },
    relayActive: { key: "ah-relay-node-active", url: "assets/world_exploration/relay_fringe_01/dead_relay_node_active.webp" },
    entrance: { key: "ah-relay-entrance", url: "assets/world_exploration/relay_fringe_01/relay_breach_entrance.webp" },
    pylon: { key: "ah-relay-pylon", url: "assets/world_exploration/relay_fringe_01/relay_fractured_pylon.webp" },
    sentinelIdle: { key: "ah-relay-sentinel-idle", url: "assets/world_exploration/relay_fringe_01/relay_sentinel_idle.webp" },
    sentinelAttack: { key: "ah-relay-sentinel-attack", url: "assets/world_exploration/relay_fringe_01/relay_sentinel_attack.webp" },
    sentinelDefeated: { key: "ah-relay-sentinel-defeated", url: "assets/world_exploration/relay_fringe_01/relay_sentinel_defeated.webp" },
    duelBarrier: { key: "ah-relay-duel-barrier", url: "assets/world_exploration/relay_fringe_01/relay_duel_barrier.webp" },
    boundaryH: { key: "ah-relay-boundary-h", url: "assets/world_exploration/relay_fringe_01/relay_boundary_fractured_h_a.webp" },
    boundaryHB: { key: "ah-relay-boundary-h-b", url: "assets/world_exploration/relay_fringe_01/relay_boundary_fractured_h_b.webp" },
    boundaryV: { key: "ah-relay-boundary-v", url: "assets/world_exploration/relay_fringe_01/relay_boundary_fractured_v_a.webp" },
    exit: { key: "ah-relay-exit", url: "assets/dojo/v1/processed/exit_gate.webp" },
    player: { key: "ah-relay-player-sheet-v1", url: "assets/dojo/v1/processed/alpha_husky_player_sheet_v1.png" },
    chaser: { key: "ah-relay-chaser-sheet-v1", url: "assets/world_exploration/relay_fringe_01/corrupted_husky_chaser_sheet_4x4_256.png" },
    loot: { key: "ah-relay-loot-sheet-v1", url: "assets/world_exploration/relay_fringe_01/loot_pickups_sheet_2x2_256.png" },
    slash: { key: "ah-relay-slash-sheet-v1", url: "assets/world_exploration/relay_fringe_01/melee_slash_sheet_5x256.png" }
  });
  const S = { tg: null, apiPost: null, dbg: false, trace: null, devPreview: false, root: null, canvasParent: null, loading: null, game: null, scene: null, opening: null, closing: false, ready: false, generation: 0, resolveReady: null, rejectReady: null, readyTimer: null, pageStyles: null, navRegistered: false, onClose: null, completedRunIds: new Set(), safeInsets: { top: 0, right: 0, bottom: 0, left: 0 } };

  function log(message, detail) { if (S.dbg) try { console.debug("[RelayFringe] " + message, detail || ""); } catch (_) {} }
  function trace(stage) { try { (S.trace || global.__AH_RELAY_STARTUP_TRACE)?.(stage); } catch (_) {} }
  function isTouch() { return global.__AH_EXPLORATION_FORCE_TOUCH === true || !!global.matchMedia?.("(pointer: coarse)")?.matches; }
  function runId() { return global.AlphaSectorCombatConfig?.makeRunId?.("relay_fringe", SECTOR.sectorId) || (typeof global.AH_makeRunId === "function" ? global.AH_makeRunId("relay_fringe", SECTOR.sectorId) : "relay_fringe_" + Date.now() + "_" + Math.random().toString(36).slice(2, 8)); }
  function sq(a, b) { const x = a.x - b.x, y = a.y - b.y; return x * x + y * y; }
  function inRange(a, b, range) { return sq(a, b) <= range * range; }

  function injectCSS() {
    if (document.getElementById(STYLE_ID)) return;
    const style = document.createElement("style"); style.id = STYLE_ID;
    style.textContent = `
.ah-exploration-room{position:fixed;inset:0;z-index:12060;display:grid;grid-template-rows:auto minmax(0,1fr);height:100dvh;overflow:hidden;background:#05090d;color:#e8f3ff;font-family:Inter,system-ui,sans-serif;touch-action:none;overscroll-behavior:none}
.ah-exploration-room__header{min-height:56px;display:grid;grid-template-columns:76px minmax(0,1fr) 76px;align-items:center;gap:8px;padding:max(8px,env(safe-area-inset-top)) max(10px,env(safe-area-inset-right)) 8px max(10px,env(safe-area-inset-left));background:linear-gradient(#111a23,#091018);border-bottom:1px solid rgba(101,232,255,.24)}
.ah-exploration-room__back{min-height:40px;border:1px solid rgba(151,188,207,.3);border-radius:9px;background:#101a25;color:#dcecff;font:700 11px/1 system-ui;letter-spacing:.08em;text-transform:uppercase;touch-action:manipulation}.ah-exploration-room__heading{text-align:center;min-width:0}.ah-exploration-room__heading span{display:block;color:#7f96a8;font-size:9px;font-weight:800;letter-spacing:.17em}.ah-exploration-room__heading strong{display:block;margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:15px;letter-spacing:.04em}.ah-exploration-room__seal{color:#65e8ff;text-align:center;font-size:10px;letter-spacing:.12em}
.ah-exploration-room__stage,.ah-exploration-room__canvas{position:relative;min-width:0;min-height:0;overflow:hidden;touch-action:none}.ah-exploration-room__canvas{position:absolute;inset:0}.ah-exploration-room__canvas canvas{display:block!important;width:100%!important;height:100%!important;touch-action:none!important}.ah-exploration-room__loading{position:absolute;inset:0;display:grid;place-items:center;background:radial-gradient(circle at 50% 44%,rgba(26,76,92,.22),transparent 45%),#071019;color:#9cb2c3;font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;pointer-events:none}.ah-exploration-room__loading[hidden]{display:none!important}
.ah-sector-result{position:absolute;inset:0;z-index:20;display:grid;place-items:center;padding:18px;background:rgba(3,7,11,.72);pointer-events:auto}.ah-sector-result__card{width:min(92vw,380px);padding:22px 18px;border:1px solid rgba(101,232,255,.55);border-radius:15px;background:linear-gradient(160deg,rgba(16,35,45,.98),rgba(7,13,20,.98));box-shadow:0 18px 50px rgba(0,0,0,.55);text-align:center}.ah-sector-result__card--failed{border-color:rgba(255,128,151,.65)}.ah-sector-result__eyebrow{font-size:10px;font-weight:800;letter-spacing:.14em;color:#80a3b6}.ah-sector-result h2{margin:6px 0 4px;font-size:23px}.ah-sector-result p{margin:0;color:#c5d6df;font-size:13px}.ah-sector-result dl{display:grid;grid-template-columns:1fr auto;gap:7px 14px;margin:18px 0;text-align:left;font-size:13px}.ah-sector-result dt{color:#8aa3b2}.ah-sector-result dd{margin:0;color:#effaff;font-weight:800}.ah-sector-result__actions{display:grid;gap:9px}.ah-sector-result button{min-height:43px;border:1px solid rgba(143,245,255,.72);border-radius:9px;background:#174755;color:#e5fdff;font:800 12px system-ui;letter-spacing:.06em}.ah-sector-result button[data-sector-run-action="map"]{border-color:rgba(201,215,230,.38);background:#17212c;color:#dce8f6}
@media(max-width:380px){.ah-exploration-room__header{grid-template-columns:66px minmax(0,1fr) 54px}.ah-exploration-room__back{font-size:10px}.ah-exploration-room__seal{font-size:8px}}
`;
    document.head.appendChild(style);
  }
  function buildShell() {
    document.getElementById(ROOT_ID)?.remove();
    const root = document.createElement("section"); root.id = ROOT_ID; root.className = "ah-exploration-room"; root.setAttribute("role", "dialog"); root.setAttribute("aria-modal", "true"); root.setAttribute("aria-label", SECTOR.displayName);
    root.innerHTML = `<header class="ah-exploration-room__header"><button type="button" class="ah-exploration-room__back" data-exploration-room-action="back">Back</button><div class="ah-exploration-room__heading"><span>RELAY FRINGE 01</span><strong>SIGNAL APPROACH</strong></div><span class="ah-exploration-room__seal">LOCAL</span></header><div class="ah-exploration-room__stage"><div id="${CANVAS_ID}" class="ah-exploration-room__canvas"></div><div class="ah-exploration-room__loading" role="status">Entering signal approach...</div></div>`;
    document.body.appendChild(root); S.root = root; S.canvasParent = root.querySelector("#" + CANVAS_ID); S.loading = root.querySelector(".ah-exploration-room__loading");
  }
  function lockPage() { if (S.pageStyles) return; const b = document.body.style, h = document.documentElement.style; S.pageStyles = { bo: b.overflow, bt: b.touchAction, bs: b.overscrollBehavior, ho: h.overflow, ht: h.touchAction, hs: h.overscrollBehavior }; b.overflow = h.overflow = "hidden"; b.touchAction = h.touchAction = "none"; b.overscrollBehavior = h.overscrollBehavior = "none"; }
  function restorePage() { if (!S.pageStyles) return; const s = S.pageStyles, b = document.body.style, h = document.documentElement.style; b.overflow = s.bo; b.touchAction = s.bt; b.overscrollBehavior = s.bs; h.overflow = s.ho; h.touchAction = s.ht; h.overscrollBehavior = s.hs; S.pageStyles = null; }
  function readInsets() { if (!S.root) return; const p = document.createElement("i"); p.style.cssText = "position:absolute;visibility:hidden;padding:env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left)"; S.root.appendChild(p); const c = getComputedStyle(p); S.safeInsets = { top: parseFloat(c.paddingTop) || 0, right: parseFloat(c.paddingRight) || 0, bottom: parseFloat(c.paddingBottom) || 0, left: parseFloat(c.paddingLeft) || 0 }; p.remove(); }
  function registerNavigation() { if (global.AlphaNav?.push) { global.AlphaNav.push(ROOT_ID, { close: () => void close({ fromNavigation: true }), isOpen, fallback: false }); S.navRegistered = true; } }
  function unregisterNavigation(fromNavigation) { if (!S.navRegistered) return; if (!fromNavigation) try { global.navClose?.(ROOT_ID); } catch (_) {} try { global.navUnregister?.(ROOT_ID); } catch (_) {} S.navRegistered = false; }
  function onResize() { if (!S.game || !S.canvasParent) return; readInsets(); const w = Math.max(1, S.canvasParent.clientWidth || global.innerWidth || 1), h = Math.max(1, S.canvasParent.clientHeight || global.innerHeight || 1); try { S.game.scale.resize(w, h); S.scene?.ahLayout?.(w, h, S.safeInsets); } catch (error) { log("resize", error); } }
  function onVisibility() { const scene = S.scene; if (!scene) return; if (document.hidden) { scene.ahPaused = true; scene.ahResetInput?.(); scene.ahStop?.(); scene.physics.world.pause(); } else if (scene.ahPaused && !S.closing) { scene.ahPaused = false; scene.physics.world.resume(); } }
  function onRootClick(event) { const action = event.target.closest?.("[data-exploration-room-action],[data-sector-run-action]")?.getAttribute("data-exploration-room-action") || event.target.closest?.("[data-sector-run-action]")?.getAttribute("data-sector-run-action"); if (action === "back" || action === "map") void close(); else if (action === "again" || action === "restart") startRun(S.scene); }
  function bindEvents() { S.root.addEventListener("click", onRootClick); global.addEventListener("resize", onResize); document.addEventListener("visibilitychange", onVisibility); try { S.tg?.onEvent?.("viewportChanged", onResize); } catch (_) {} }
  function unbindEvents() { S.root?.removeEventListener("click", onRootClick); global.removeEventListener("resize", onResize); document.removeEventListener("visibilitychange", onVisibility); try { S.tg?.offEvent?.("viewportChanged", onResize); } catch (_) {} }

  function makeAnimations(scene) {
    const playerDirs = ["down", "up", "right", "left"];
    if (scene.textures.exists(ASSETS.player.key)) playerDirs.forEach((dir, row) => { const idle = "ah-relay-player-" + dir + "-idle", walk = "ah-relay-player-" + dir + "-walk"; if (!scene.anims.exists(idle)) scene.anims.create({ key: idle, frames: [{ key: ASSETS.player.key, frame: row * 4 }], repeat: -1 }); if (!scene.anims.exists(walk)) scene.anims.create({ key: walk, frames: [1, 2, 3, 2].map(n => ({ key: ASSETS.player.key, frame: row * 4 + n })), frameRate: 7, repeat: -1 }); });
    playerDirs.forEach((dir, row) => { const idle = "ah-relay-chaser-" + dir + "-idle", walk = "ah-relay-chaser-" + dir + "-walk"; if (!scene.anims.exists(idle)) scene.anims.create({ key: idle, frames: [{ key: ASSETS.chaser.key, frame: row * 4 }], repeat: -1 }); if (!scene.anims.exists(walk)) scene.anims.create({ key: walk, frames: [1, 2, 3, 2].map(n => ({ key: ASSETS.chaser.key, frame: row * 4 + n })), frameRate: 7, repeat: -1 }); });
    if (!scene.anims.exists("ah-relay-slash")) scene.anims.create({ key: "ah-relay-slash", frames: [0, 1, 2, 3, 4].map(frame => ({ key: ASSETS.slash.key, frame })), frameRate: 26, hideOnComplete: true });
  }
  function setAnimation(sprite, prefix, direction, moving) { const key = prefix + "-" + (direction || sprite.ahDirection || "down") + (moving ? "-walk" : "-idle"); sprite.ahDirection = direction || sprite.ahDirection || "down"; if (sprite.anims?.currentAnim?.key !== key) sprite.play?.(key); }
  function addBlock(scene, group, x, y, width, height, fill = 0x172630) { const block = scene.add.rectangle(x, y, width, height, fill, .94).setStrokeStyle(2, 0x426574, .8).setDepth(9); scene.physics.add.existing(block, true); group.add(block); return block; }
  function addCollider(scene, group, x, y, width, height) { const collider = scene.add.rectangle(x, y, width, height, 0x000000, 0).setVisible(false); scene.physics.add.existing(collider, true); group.add(collider); return collider; }
  function addArt(scene, asset, x, y, scale, depth, options) { if (!scene.textures.exists(asset.key)) return null; const image = scene.add.image(x, y, asset.key).setScale(scale).setDepth(depth); if (options?.origin) image.setOrigin(options.origin[0], options.origin[1]); if (options?.flipX) image.setFlipX(true); return image; }
  function buildWorld(scene) {
    if (scene.textures.exists(ASSETS.floor.key)) [350, 1050].forEach(x => [350, 1050].forEach(y => scene.add.image(x, y, ASSETS.floor.key).setScale(.56).setDepth(0))); else scene.add.rectangle(WORLD.width / 2, WORLD.height / 2, WORLD.width, WORLD.height, 0x0b151d, 1).setDepth(0);
    const blockers = scene.physics.add.staticGroup(); scene.ahBlockers = blockers;
    addBlock(scene, blockers, WORLD.width / 2, 25, WORLD.width, 50); addBlock(scene, blockers, WORLD.width / 2, WORLD.height - 25, WORLD.width, 50); addBlock(scene, blockers, 25, WORLD.height / 2, 50, WORLD.height); addBlock(scene, blockers, WORLD.width - 25, WORLD.height / 2, 50, WORLD.height);
    [[406, 634, 222, 42], [606, 420, 194, 42], [824, 592, 220, 42], [1110, 470, 180, 42], [708, 218, 44, 212], [908, 192, 44, 184], [1072, 754, 176, 46]].forEach(v => addBlock(scene, blockers, ...v));
    scene.ahBreachEntrance = addArt(scene, ASSETS.entrance, 210, 735, .28, 12, { origin: [.5, .82] }); scene.ahEntranceSupports = [addCollider(scene, blockers, 82, 687, 44, 82), addCollider(scene, blockers, 338, 687, 44, 82)]; scene.ahPylonVisual = addArt(scene, ASSETS.pylon, 1080, 590, .19, 20, { origin: [.5, .86] }); scene.ahPylonCollider = addCollider(scene, blockers, 1080, 590, 78, 58); addArt(scene, ASSETS.boundaryH, 406, 634, .27, 10); addArt(scene, ASSETS.boundaryHB, 606, 420, .24, 10); addArt(scene, ASSETS.boundaryH, 824, 592, .27, 10, { flipX: true }); addArt(scene, ASSETS.boundaryHB, 1110, 470, .24, 10, { flipX: true }); addArt(scene, ASSETS.boundaryV, 708, 218, .5, 10); addArt(scene, ASSETS.boundaryV, 908, 192, .5, 10);
    scene.add.text(110, 108, "PACK BOUNDARY // SIGNAL APPROACH", { fontFamily: "system-ui", fontSize: "14px", color: "#7190a0", letterSpacing: 2 }).setDepth(3);
    scene.ahNode = addArt(scene, ASSETS.relayIdle, WORLD.relay.x, WORLD.relay.y, .16, 14) || scene.add.rectangle(WORLD.relay.x, WORLD.relay.y, 136, 150, 0x172f39, .96).setStrokeStyle(3, 0x54727f, .95).setDepth(14);
    scene.ahNodeAnchor = { x: WORLD.relay.x, y: WORLD.relay.y + 66 }; scene.ahNodeLabel = scene.add.text(WORLD.relay.x, WORLD.relay.y - 94, "RELAY LOCKED", { fontFamily: "system-ui", fontSize: "12px", color: "#e8af91", fontStyle: "bold" }).setOrigin(.5).setDepth(16); scene.ahNodeGlow = scene.add.circle(WORLD.relay.x, WORLD.relay.y + 58, 78, 0x65e8ff, .02).setStrokeStyle(2, 0x65e8ff, .16).setDepth(13);
    scene.ahExitVisual = addArt(scene, ASSETS.exit, WORLD.exit.x, WORLD.exit.y, .22, 12) || scene.add.rectangle(WORLD.exit.x, WORLD.exit.y, 150, 82, 0x173b44, .65).setStrokeStyle(2, 0x65e8ff, .8).setDepth(12); scene.ahExitGlow = scene.add.circle(WORLD.exit.x, WORLD.exit.y, 92, 0x65e8ff, .02).setStrokeStyle(2, 0x53636a, .22).setDepth(11); setRelayState(scene, "locked"); setExitState(scene, false);
    if (scene.textures.exists(ASSETS.player.key)) { scene.ahPlayer = scene.physics.add.sprite(WORLD.playerSpawn.x, WORLD.playerSpawn.y, ASSETS.player.key, 8).setScale(.32).setDepth(30); scene.ahPlayer.body.setSize(70, 90).setOffset(93, 150); } else { scene.ahPlayer = scene.add.rectangle(WORLD.playerSpawn.x, WORLD.playerSpawn.y, 54, 70, 0x65e8ff, .96).setStrokeStyle(3, 0xdffcff, .95).setDepth(30); scene.physics.add.existing(scene.ahPlayer); scene.ahPlayer.body.setSize(54, 70); scene.ahPlayerFallback = true; } scene.ahPlayer.setCollideWorldBounds(true); setAnimation(scene.ahPlayer, "ah-relay-player", "right", false); scene.physics.add.collider(scene.ahPlayer, blockers);
    scene.ahEnemies = scene.physics.add.group(); scene.ahLoot = scene.physics.add.group(); scene.ahEnemyUi = []; scene.physics.add.collider(scene.ahEnemies, blockers); scene.physics.add.collider(scene.ahEnemies, scene.ahEnemies); scene.physics.add.collider(scene.ahPlayer, scene.ahEnemies); scene.physics.add.overlap(scene.ahPlayer, scene.ahLoot, collectLoot, undefined, scene);
    if (LEGACY_RELAY_FEATURES.sentinelEncounter) installLegacySentinelEncounter(scene);
  }
  function setRelayState(scene, state) { scene.ahRelayState = state; const active = state === "available" || state === "activated"; const restored = state === "activated"; if (scene.ahNode?.setTexture && scene.textures.exists(restored ? ASSETS.relayActive.key : ASSETS.relayIdle.key)) scene.ahNode.setTexture(restored ? ASSETS.relayActive.key : ASSETS.relayIdle.key); scene.ahNode?.setTint?.(state === "locked" ? 0x7e8a91 : 0xffffff); scene.ahNodeGlow?.setAlpha(active ? .22 : .02).setStrokeStyle(2, active ? 0x65e8ff : 0x53636a, active ? .84 : .18); scene.ahNodeLabel?.setText(state === "locked" ? "RELAY LOCKED" : restored ? "RELAY ACTIVE" : "RELAY READY").setColor(state === "locked" ? "#e8af91" : "#baf6ff"); }
  function setExitState(scene, active) { scene.ahExitActive = !!active; scene.ahExitVisual?.setTint?.(active ? 0xbffaff : 0x53636a); scene.ahExitVisual?.setAlpha?.(active ? 1 : .42); scene.ahExitGlow?.setAlpha(active ? .18 : .025).setStrokeStyle(2, active ? 0x65e8ff : 0x53636a, active ? .72 : .22); }

  function createControls(scene) {
    scene.ahMove = new global.Phaser.Math.Vector2(); scene.ahJoy = { x: 0, y: 0 }; scene.ahJoyPointer = null; scene.ahAttackPointer = null; scene.ahRelayPointer = null; scene.ahContext = null; scene.ahTouch = isTouch(); scene.ahPaused = false;
    scene.ahJoyBase = scene.add.circle(88, 88, 54, 0x0b1620, .75).setStrokeStyle(2, 0x65e8ff, .5).setScrollFactor(0).setDepth(100); scene.ahJoyThumb = scene.add.circle(88, 88, 25, 0x65e8ff, .3).setStrokeStyle(2, 0xbaf6ff, .75).setScrollFactor(0).setDepth(101); scene.ahJoyHit = scene.add.zone(88, 88, 160, 160).setInteractive().setScrollFactor(0).setDepth(102);
    scene.ahAttackRing = scene.add.circle(0, 0, 40, 0x3b122d, .9).setStrokeStyle(2, 0xff70bd, .94).setScrollFactor(0).setDepth(100); scene.ahAttackLabel = scene.add.text(0, 0, "ATTACK", { fontFamily: "system-ui", fontSize: "10px", color: "#ffd1e8", fontStyle: "bold" }).setOrigin(.5).setScrollFactor(0).setDepth(101); scene.ahAttackHit = scene.add.zone(0, 0, 96, 96).setInteractive().setScrollFactor(0).setDepth(102);
    scene.ahRelayRing = scene.add.circle(0, 0, 36, 0x17606c, .94).setStrokeStyle(2, 0xb7fbff, .96).setScrollFactor(0).setDepth(106).setVisible(false); scene.ahRelayLabel = scene.add.text(0, 0, "ACTIVATE", { fontFamily: "system-ui", fontSize: "8px", color: "#e4feff", fontStyle: "bold" }).setOrigin(.5).setScrollFactor(0).setDepth(107).setVisible(false); scene.ahRelayHit = scene.add.zone(0, 0, 88, 88).setInteractive().setScrollFactor(0).setDepth(108).setVisible(false); scene.ahRelayHit.input.enabled = false;
    scene.ahDashRing = scene.add.circle(0, 0, 29, 0x1a3041, .92).setStrokeStyle(2, 0x9ff7ff, .82).setScrollFactor(0).setDepth(103).setVisible(false); scene.ahDashLabel = scene.add.text(0, 0, "DASH", { fontFamily: "system-ui", fontSize: "8px", color: "#dffcff", fontStyle: "bold" }).setOrigin(.5).setScrollFactor(0).setDepth(104).setVisible(false); scene.ahDashHit = scene.add.zone(0, 0, 62, 62).setInteractive().setScrollFactor(0).setDepth(105).setVisible(false); scene.ahDashHit.input.enabled = false; scene.ahNextDashAt = 0;
    scene.ahPrompt = scene.add.text(0, 0, "", { fontFamily: "system-ui", fontSize: "12px", color: "#a9edf7", fontStyle: "bold", align: "center" }).setOrigin(.5, 0).setScrollFactor(0).setDepth(102); scene.ahMessage = scene.add.text(0, 0, "", { fontFamily: "system-ui", fontSize: "13px", color: "#d8fbff", fontStyle: "bold", align: "center", backgroundColor: "rgba(5,10,15,.70)", padding: { x: 10, y: 6 } }).setOrigin(.5).setScrollFactor(0).setDepth(103).setVisible(false); scene.ahHud = scene.add.text(14, 16, "", { fontFamily: "system-ui", fontSize: "11px", color: "#dff8ff", fontStyle: "bold", backgroundColor: "rgba(5,10,15,.68)", padding: { x: 8, y: 6 } }).setScrollFactor(0).setDepth(150); scene.ahTargetLabel = scene.add.text(14, 54, "", { fontFamily: "system-ui", fontSize: "11px", color: "#ffb6db", fontStyle: "bold", backgroundColor: "rgba(5,10,15,.68)", padding: { x: 8, y: 6 } }).setScrollFactor(0).setDepth(150); scene.ahTargetRing = scene.add.circle(0, 0, 31, 0xff70bd, 0).setStrokeStyle(2, 0xff9bca, .9).setDepth(22).setVisible(false);
    scene.ahOnJoyDown = p => { if (scene.ahJoyPointer === null && scene.input.enabled) { scene.ahJoyPointer = p.id; updateJoy(scene, p); } }; scene.ahOnAttackDown = p => { if (scene.ahAttackPointer === null && scene.input.enabled) { scene.ahAttackPointer = p.id; playerAttack(scene); } }; scene.ahOnRelayDown = p => { if (scene.ahRelayPointer === null && scene.input.enabled && scene.ahContext === "relay") { scene.ahRelayPointer = p.id; activateRelay(scene); } }; scene.ahOnDashDown = p => { if (scene.input.enabled) legacyDash(scene); }; scene.ahOnMove = p => { if (p.id === scene.ahJoyPointer) updateJoy(scene, p); }; scene.ahOnUp = p => { if (p.id === scene.ahJoyPointer) resetJoy(scene); if (p.id === scene.ahAttackPointer) scene.ahAttackPointer = null; if (p.id === scene.ahRelayPointer) scene.ahRelayPointer = null; }; scene.ahOnGameOut = () => scene.ahResetInput();
    scene.ahJoyHit.on("pointerdown", scene.ahOnJoyDown); scene.ahAttackHit.on("pointerdown", scene.ahOnAttackDown); scene.ahRelayHit.on("pointerdown", scene.ahOnRelayDown); scene.ahDashHit.on("pointerdown", scene.ahOnDashDown); scene.input.on("pointermove", scene.ahOnMove); scene.input.on("pointerup", scene.ahOnUp); scene.input.on("gameout", scene.ahOnGameOut);
    scene.ahResetInput = () => { resetJoy(scene); scene.ahAttackPointer = null; scene.ahRelayPointer = null; }; scene.ahStop = () => { scene.ahPlayer?.setVelocity(0, 0); setAnimation(scene.ahPlayer, "ah-relay-player", scene.ahPlayer?.ahDirection, false); }; scene.ahLayout = (w, h, insets) => layout(scene, w, h, insets); layout(scene, scene.scale.width, scene.scale.height, S.safeInsets);
  }
  function layout(scene, w, h, insets) { const compact = w < 430, joyX = Math.max(72, insets.left + (compact ? 72 : 88)), y = h - Math.max(76, insets.bottom + (compact ? 76 : 90)), attackX = w - Math.max(64, insets.right + (compact ? 64 : 78)), relayX = Math.max(joyX + 98, attackX - (compact ? 82 : 92)), dashX = relayX - (compact ? 70 : 78); scene.ahJoyBase.setPosition(joyX, y); scene.ahJoyHit.setPosition(joyX, y); if (scene.ahJoyPointer === null) scene.ahJoyThumb.setPosition(joyX, y); [scene.ahAttackRing, scene.ahAttackLabel, scene.ahAttackHit].forEach(item => item.setPosition(attackX, y)); [scene.ahRelayRing, scene.ahRelayLabel, scene.ahRelayHit].forEach(item => item.setPosition(relayX, y)); [scene.ahDashRing, scene.ahDashLabel, scene.ahDashHit].forEach(item => item.setPosition(dashX, y + 4)); scene.ahPrompt.setPosition(w / 2, Math.max(12, insets.top + 12)); scene.ahMessage.setPosition(w / 2, Math.max(54, insets.top + 54)); scene.ahHud.setPosition(Math.max(10, insets.left + 10), Math.max(10, insets.top + 10)); scene.ahTargetLabel.setPosition(Math.max(10, insets.left + 10), Math.max(48, insets.top + 48)); updateLegacyDashControl(scene); }
  function updateJoy(scene, p) { let x = p.x - scene.ahJoyBase.x, y = p.y - scene.ahJoyBase.y, d = Math.hypot(x, y); if (d > 48) { x *= 48 / d; y *= 48 / d; } scene.ahJoyThumb.setPosition(scene.ahJoyBase.x + x, scene.ahJoyBase.y + y); if (d < 11) { scene.ahJoy.x = scene.ahJoy.y = 0; return; } d = Math.hypot(x, y) || 1; scene.ahJoy.x = x / d; scene.ahJoy.y = y / d; }
  function resetJoy(scene) { scene.ahJoyPointer = null; scene.ahJoy.x = scene.ahJoy.y = 0; scene.ahJoyThumb?.setPosition(scene.ahJoyBase.x, scene.ahJoyBase.y); }
  function createKeyboard(scene) { if (!scene.input.keyboard) return; scene.ahCursors = scene.input.keyboard.createCursorKeys(); scene.ahKeys = scene.input.keyboard.addKeys({ up: global.Phaser.Input.Keyboard.KeyCodes.W, left: global.Phaser.Input.Keyboard.KeyCodes.A, down: global.Phaser.Input.Keyboard.KeyCodes.S, right: global.Phaser.Input.Keyboard.KeyCodes.D, interact: global.Phaser.Input.Keyboard.KeyCodes.E, attack: global.Phaser.Input.Keyboard.KeyCodes.F, space: global.Phaser.Input.Keyboard.KeyCodes.SPACE, dash: global.Phaser.Input.Keyboard.KeyCodes.SHIFT, escape: global.Phaser.Input.Keyboard.KeyCodes.ESC }); }

  function makeRunState() { return { runId: runId(), sectorId: SECTOR.sectorId, status: "active", startedAt: Date.now(), duration: 0, requiredEnemies: LEGACY_RELAY_FEATURES.sentinelEncounter ? 1 : SECTOR.requiredEnemies, enemiesKilled: 0, playerHP: COMBAT.playerMaxHp, expEarned: 0, bonesEarned: 0, scrapEarned: 0, equipmentDrops: 0, relayActivated: false }; }
  function clearRunObjects(scene) { scene.ahEnemies?.clear(true, true); scene.ahLoot?.clear(true, true); scene.ahEnemyUi?.forEach(item => item.destroy?.()); scene.ahEnemyUi = []; scene.ahTargetRing?.setVisible(false); removeResultPanel(); }
  function startRun(scene) {
    if (!scene || S.closing) return;
    clearRunObjects(scene); scene.input.enabled = true; scene.ahRun = makeRunState(); scene.ahPlayerControl = true; scene.ahNextAttackAt = 0; scene.ahPlayer.enableBody(true, WORLD.playerSpawn.x, WORLD.playerSpawn.y, true, true).setAlpha(1).clearTint(); scene.ahPlayer.setVelocity(0, 0); setAnimation(scene.ahPlayer, "ah-relay-player", "right", false); setRelayState(scene, "locked"); setExitState(scene, false);
    if (LEGACY_RELAY_FEATURES.sentinelEncounter) { scene.ahLegacySentinelState = "dormant"; scene.ahLegacySentinel?.setPosition(scene.ahLegacyArena.sentinelX, scene.ahLegacyArena.sentinelY); scene.ahLegacySentinel?.body?.reset(scene.ahLegacySentinel.x, scene.ahLegacySentinel.y); scene.ahLegacySentinel?.setVisible(!scene.ahLegacySentinelVisual); scene.ahLegacySentinelVisual?.setTexture(ASSETS.sentinelIdle.key).setVisible(true); setLegacyBarrier(scene, false); } else ENEMY_SPAWNS.forEach(spawn => spawnChaser(scene, spawn)); updateHud(scene); setContext(scene, null); showMessage(scene, "SIGNAL APPROACH ACTIVE");
  }
  function spawnChaser(scene, spawn) { const enemy = scene.physics.add.sprite(spawn.x, spawn.y, ASSETS.chaser.key, 0).setScale(.25).setDepth(25).setCollideWorldBounds(true); enemy.body.setSize(78, 80).setOffset(89, 142); enemy.ahCombat = { hp: COMBAT.enemyMaxHp, nextAttackAt: 0, dead: false }; setAnimation(enemy, "ah-relay-chaser", "down", false); const back = scene.add.rectangle(enemy.x, enemy.y - 46, 34, 6, 0x150b17, .94).setDepth(40), bar = scene.add.rectangle(enemy.x, enemy.y - 46, 32, 4, 0xff5fa8, .98).setDepth(41), label = scene.add.text(enemy.x, enemy.y - 62, "CORRUPTED CHASER", { fontFamily: "system-ui", fontSize: "9px", color: "#ff9bca", fontStyle: "bold", letterSpacing: 1 }).setOrigin(.5).setDepth(40); enemy.ahUi = [back, bar, label]; scene.ahEnemyUi.push(...enemy.ahUi); scene.ahEnemies.add(enemy); }
  function updateEnemyUi(enemy) { if (!enemy?.active || !enemy.ahCombat) return; const ratio = Math.max(0, enemy.ahCombat.hp / COMBAT.enemyMaxHp), [back, bar, label] = enemy.ahUi; back.setPosition(enemy.x, enemy.y - 46); bar.setPosition(enemy.x - 16 + 16 * ratio, enemy.y - 46).setDisplaySize(32 * ratio, 4); label.setPosition(enemy.x, enemy.y - 62); }
  function nearestEnemy(scene) { const player = scene.ahPlayer; if (!player?.active) return null; let closest = null, distanceSq = Infinity; scene.ahEnemies.children.iterate(enemy => { if (!enemy?.active || enemy.ahCombat?.dead) return; const d = sq(player, enemy); if (d < distanceSq) { closest = enemy; distanceSq = d; } }); return closest ? { enemy: closest, distanceSq } : null; }
  function updateHud(scene) { const run = scene.ahRun; if (!run) return; run.playerHP = Math.max(0, run.playerHP); scene.ahHud.setText("HP  " + run.playerHP + " / " + COMBAT.playerMaxHp + "\nCHASERS  " + run.enemiesKilled + " / " + run.requiredEnemies + "\nEXP  " + run.expEarned + "  BONES  " + run.bonesEarned + "  SCRAP  " + run.scrapEarned + "  GEAR  " + run.equipmentDrops); }
  function showMessage(scene, text) { scene.ahMessageTimer?.remove?.(false); scene.ahMessage.setText(text).setVisible(true); scene.ahMessageTimer = scene.time.delayedCall(1500, () => scene.ahMessage?.setVisible(false)); }
  function setContext(scene, context) { if (scene.ahContext === context) return; scene.ahContext = context; const relay = context === "relay", failed = scene.ahRun?.status === "failed" || scene.ahRun?.status === "completed"; scene.ahRelayRing.setVisible(relay && scene.ahTouch); scene.ahRelayLabel.setVisible(relay && scene.ahTouch); scene.ahRelayHit.setVisible(relay && scene.ahTouch); scene.ahRelayHit.input.enabled = relay && scene.ahTouch && !failed; if (relay) scene.ahPrompt.setText(scene.ahTouch ? "RELAY READY - ACTIVATE" : "RELAY READY - E TO ACTIVATE"); else if (context === "exit") scene.ahPrompt.setText(scene.ahTouch ? "EXIT TO MAP" : "EXIT TO MAP - E"); else scene.ahPrompt.setText(scene.ahTouch ? "" : "WASD / ARROWS - MOVE - F / SPACE ATTACK"); }
  function updatePlayer(scene) { const run = scene.ahRun, movable = run?.status === "active" || run?.status === "cleared"; if (!scene.ahPlayerControl || !movable) { scene.ahStop(); return; } let x = scene.ahJoy.x, y = scene.ahJoy.y, k = scene.ahKeys, c = scene.ahCursors; if (k?.left?.isDown || c?.left?.isDown) x--; if (k?.right?.isDown || c?.right?.isDown) x++; if (k?.up?.isDown || c?.up?.isDown) y--; if (k?.down?.isDown || c?.down?.isDown) y++; const move = scene.ahMove.set(x, y); if (move.lengthSq() > 0) { move.normalize().scale(COMBAT.playerSpeed); scene.ahPlayer.setVelocity(move.x, move.y); setAnimation(scene.ahPlayer, "ah-relay-player", Math.abs(move.x) > Math.abs(move.y) ? (move.x < 0 ? "left" : "right") : (move.y < 0 ? "up" : "down"), true); } else { scene.ahPlayer.setVelocity(0, 0); setAnimation(scene.ahPlayer, "ah-relay-player", scene.ahPlayer.ahDirection, false); } }
  function updateLegacyDashControl(scene) { const enabled = LEGACY_RELAY_FEATURES.dash && !!scene.ahPlayerControl && (scene.ahRun?.status === "active" || scene.ahRun?.status === "cleared"), ready = scene.time.now >= (scene.ahNextDashAt || 0); scene.ahDashRing?.setVisible(enabled).setAlpha(ready ? 1 : .35); scene.ahDashLabel?.setVisible(enabled).setAlpha(ready ? 1 : .4); scene.ahDashHit?.setVisible(enabled); if (scene.ahDashHit?.input) scene.ahDashHit.input.enabled = enabled; }
  function legacyDash(scene) { if (!LEGACY_RELAY_FEATURES.dash || !scene.ahPlayerControl || scene.time.now < (scene.ahNextDashAt || 0)) return; const player = scene.ahPlayer, v = scene.ahMove.clone(); if (v.lengthSq() < 1) { const directions = { left: [-1, 0], right: [1, 0], up: [0, -1], down: [0, 1] }, direction = directions[player.ahDirection] || directions.right; v.set(direction[0], direction[1]); } v.normalize(); scene.ahNextDashAt = scene.time.now + 1750; player.setVelocity(v.x * 560, v.y * 560); const trail = scene.add.circle(player.x, player.y, 18, 0x65e8ff, .34).setDepth(26).setScale(1.25, .58); scene.tweens.add({ targets: trail, scaleX: 2.8, scaleY: .85, alpha: 0, duration: 150, onComplete: () => trail.destroy() }); scene.time.delayedCall(150, () => scene.ahRun?.status !== "failed" && player?.active && player.setVelocity(0, 0)); updateLegacyDashControl(scene); }
  // Dormant legacy Sentinel encounter. It preserves the old trigger, barrier, telegraph, lunge, recovery, and defeat path
  // without mixing that prototype with the production five-Chaser run.
  function installLegacySentinelEncounter(scene) { const arena = { left: 744, right: 1188, top: 248, bottom: 682, gateY: 465, gateHeight: 142, triggerX: 806, triggerY: 465, triggerWidth: 82, triggerHeight: 176, sentinelX: 978, sentinelY: 465 }; const walls = scene.physics.add.staticGroup(), gapTop = arena.gateY - arena.gateHeight / 2, gapBottom = arena.gateY + arena.gateHeight / 2; [[(arena.left + arena.right) / 2, arena.top, arena.right - arena.left, 34], [(arena.left + arena.right) / 2, arena.bottom, arena.right - arena.left, 34], [arena.right, 465, 34, arena.bottom - arena.top], [arena.left, (arena.top + gapTop) / 2, 34, gapTop - arena.top], [arena.left, (gapBottom + arena.bottom) / 2, 34, arena.bottom - gapBottom]].forEach(v => addBlock(scene, walls, ...v, 0x14222c)); scene.ahLegacyArena = arena; scene.ahLegacyArenaWalls = walls; scene.physics.add.collider(scene.ahPlayer, walls); const barrier = scene.add.rectangle(arena.left, arena.gateY, 54, 142, 0x5eeaff, .26).setStrokeStyle(3, 0x9ff7ff, .95).setDepth(18); scene.physics.add.existing(barrier, true); barrier.body.enable = false; scene.physics.add.collider(scene.ahPlayer, barrier); scene.ahLegacyBarrier = barrier; scene.ahLegacyBarrierVisual = addArt(scene, ASSETS.duelBarrier, arena.left, arena.gateY, .14, 19, { origin: [.507, .541] }); scene.ahLegacyBarrierVisual?.setRotation(Math.PI / 2).setVisible(false); const sentinel = scene.add.rectangle(arena.sentinelX, arena.sentinelY, 64, 64, 0x6a2337, .55).setStrokeStyle(3, 0xff6b86, .8).setDepth(27); scene.physics.add.existing(sentinel); sentinel.body.setSize(58, 58); scene.physics.add.collider(sentinel, walls); scene.ahLegacySentinel = sentinel; scene.ahLegacySentinelVisual = addArt(scene, ASSETS.sentinelIdle, arena.sentinelX, arena.sentinelY + 29, .14, 27, { origin: [.5, .92] }); sentinel.setVisible(!scene.ahLegacySentinelVisual); scene.ahLegacySentinelState = "dormant"; scene.ahLegacySentinelHp = 6; }
  function setLegacyBarrier(scene, active) { const barrier = scene.ahLegacyBarrier; if (!barrier) return; barrier.body.enable = !!active; barrier.refreshBody?.(); barrier.setVisible(!scene.ahLegacyBarrierVisual).setAlpha(active ? 1 : .28); scene.ahLegacyBarrierVisual?.setVisible(!!active); }
  function startLegacySentinel(scene) { if (!LEGACY_RELAY_FEATURES.sentinelEncounter || scene.ahLegacySentinelState !== "dormant") return; scene.ahLegacySentinelState = "idle"; scene.ahLegacySentinelHp = 6; scene.ahLegacySentinel.body.enable = true; scene.ahLegacySentinelStateUntil = scene.time.now + 800; setLegacyBarrier(scene, true); }
  function legacySentinelAttack(scene) { const sentinel = scene.ahLegacySentinel; if (scene.ahLegacySentinelState !== "recovery" || !sentinel || !inRange(scene.ahPlayer, sentinel, 120)) return false; scene.ahNextAttackAt = scene.time.now + COMBAT.playerAttackCooldownMs; showSlash(scene, sentinel); scene.ahLegacySentinelHp = Math.max(0, scene.ahLegacySentinelHp - 1); sentinel.setFillStyle(0xe8fdff, 1); scene.time.delayedCall(100, () => sentinel?.active && sentinel.setFillStyle(0x365d66, 1)); if (scene.ahLegacySentinelHp > 0) return true; sentinel.body.enable = false; sentinel.setVisible(false); scene.ahLegacySentinelVisual?.setTexture(ASSETS.sentinelDefeated.key).setVisible(true); scene.ahLegacySentinelState = "defeated"; setLegacyBarrier(scene, false); scene.ahRun.enemiesKilled = 1; updateHud(scene); clearEncounter(scene); return true; }
  function updateLegacySentinel(scene, time) { if (!LEGACY_RELAY_FEATURES.sentinelEncounter || !scene.ahLegacySentinel) return; const state = scene.ahLegacySentinelState, sentinel = scene.ahLegacySentinel, player = scene.ahPlayer, arena = scene.ahLegacyArena; if (state === "dormant") { if (global.Phaser.Geom.Rectangle.Contains(new global.Phaser.Geom.Rectangle(arena.triggerX - arena.triggerWidth / 2, arena.triggerY - arena.triggerHeight / 2, arena.triggerWidth, arena.triggerHeight), player.x, player.y)) startLegacySentinel(scene); return; } if (state === "idle") { const v = new global.Phaser.Math.Vector2(player.x - sentinel.x, player.y - sentinel.y); if (v.lengthSq() > 70 * 70) { v.normalize(); sentinel.body.setVelocity(v.x * 42, v.y * 42); } else sentinel.body.setVelocity(0, 0); if (time >= scene.ahLegacySentinelStateUntil) { scene.ahLegacySentinelState = "telegraph"; scene.ahLegacySentinelStateUntil = time + 700; const v2 = new global.Phaser.Math.Vector2(player.x - sentinel.x, player.y - sentinel.y); v2.normalize(); scene.ahLegacyLungeVector = { x: v2.x || 1, y: v2.y }; scene.ahLegacyTelegraph = scene.add.circle(sentinel.x, sentinel.y, 46, 0xff5471, .11).setStrokeStyle(3, 0xff738c, .82).setDepth(24); } } else if (state === "telegraph" && time >= scene.ahLegacySentinelStateUntil) { scene.ahLegacyTelegraph?.destroy(); scene.ahLegacyTelegraph = null; scene.ahLegacySentinelState = "lunge"; scene.ahLegacySentinelStateUntil = time + 440; scene.ahLegacyHitThisLunge = false; sentinel.body.setVelocity(scene.ahLegacyLungeVector.x * 430, scene.ahLegacyLungeVector.y * 430); scene.ahLegacySentinelVisual?.setTexture(ASSETS.sentinelAttack.key); } else if (state === "lunge") { if (!scene.ahLegacyHitThisLunge && inRange(sentinel, player, 76)) { scene.ahLegacyHitThisLunge = true; damagePlayer(scene, 1); } if (time >= scene.ahLegacySentinelStateUntil) { sentinel.body.setVelocity(0, 0); scene.ahLegacySentinelState = "recovery"; scene.ahLegacySentinelStateUntil = time + 900; scene.ahLegacySentinelVisual?.setTexture(ASSETS.sentinelIdle.key); } } else if (state === "recovery" && time >= scene.ahLegacySentinelStateUntil) { scene.ahLegacySentinelState = "idle"; scene.ahLegacySentinelStateUntil = time + 350; } scene.ahLegacySentinelVisual?.setPosition(sentinel.x, sentinel.y + 29); }
  function updateContext(scene) { const run = scene.ahRun, p = scene.ahPlayer; if (!run || !p?.active || run.status === "failed" || run.status === "completed") return setContext(scene, null); const choices = []; if (run.status === "cleared" && inRange(p, scene.ahNodeAnchor, 116)) choices.push({ key: "relay", d: sq(p, scene.ahNodeAnchor) }); if (scene.ahExitActive && inRange(p, WORLD.exit, 126)) choices.push({ key: "exit", d: sq(p, WORLD.exit) }); choices.sort((a, b) => a.d - b.d); setContext(scene, choices[0]?.key || null); }
  function showSlash(scene, enemy) { const p = scene.ahPlayer, angle = Math.atan2(enemy.y - p.y, enemy.x - p.x), x = p.x + Math.cos(angle) * 34, y = p.y + Math.sin(angle) * 34; if (scene.textures.exists(ASSETS.slash.key)) { const slash = scene.add.sprite(x, y, ASSETS.slash.key, 0).setScale(.32).setRotation(angle).setDepth(50); slash.play("ah-relay-slash"); slash.once("animationcomplete", () => slash.destroy()); return; } const slash = scene.add.arc(x, y, 24, 210, 510, false, 0x8cefff, 0).setStrokeStyle(4, 0xbaf6ff, .95).setDepth(50); scene.tweens.add({ targets: slash, alpha: 0, scaleX: 1.35, scaleY: 1.35, duration: 120, onComplete: () => slash.destroy() }); }
  function playerAttack(scene) { const run = scene.ahRun, time = scene.time.now; if (!run || run.status !== "active" || !scene.ahPlayer?.active || time < scene.ahNextAttackAt) return; if (LEGACY_RELAY_FEATURES.sentinelEncounter && legacySentinelAttack(scene)) return; const target = nearestEnemy(scene); if (!target || target.distanceSq > COMBAT.playerAttackRange * COMBAT.playerAttackRange) return; scene.ahNextAttackAt = time + COMBAT.playerAttackCooldownMs; showSlash(scene, target.enemy); damageEnemy(scene, target.enemy, COMBAT.playerDamage); }
  function damageEnemy(scene, enemy, damage) { if (!enemy?.active || enemy.ahCombat?.dead) return; enemy.ahCombat.hp = Math.max(0, enemy.ahCombat.hp - damage); enemy.setTint(0xffffff); scene.time.delayedCall(70, () => enemy?.active && !enemy.ahCombat?.dead && enemy.clearTint()); updateEnemyUi(enemy); if (enemy.ahCombat.hp === 0) killEnemy(scene, enemy); }
  function killEnemy(scene, enemy) { if (!enemy?.active || enemy.ahCombat?.dead) return; const run = scene.ahRun; enemy.ahCombat.dead = true; enemy.body.enable = false; dropLoot(scene, enemy.x, enemy.y); enemy.ahUi.forEach(item => item.destroy()); scene.ahEnemyUi = scene.ahEnemyUi.filter(item => !enemy.ahUi.includes(item)); scene.tweens.add({ targets: enemy, alpha: 0, scaleX: .32, scaleY: .32, duration: 170, onComplete: () => enemy.destroy() }); run.enemiesKilled += 1; updateHud(scene); if (run.enemiesKilled === run.requiredEnemies) clearEncounter(scene); }
  function dropLoot(scene, x, y) { Object.entries(LOOT).forEach(([kind, config]) => { if (Math.random() > config.chance) return; const pickup = scene.physics.add.sprite(x, y, ASSETS.loot.key, config.frame).setScale(.16).setDepth(24); pickup.body.setCircle(30, 98, 98); pickup.setVelocity((Math.random() - .5) * 110, -40 - Math.random() * 60).setDrag(260, 260).setMaxVelocity(100, 100); pickup.ahLoot = { kind, value: config.value, label: config.label }; scene.ahLoot.add(pickup); scene.tweens.add({ targets: pickup, angle: 360, duration: 950, repeat: -1 }); }); }
  function collectLoot(player, pickup) { if (!pickup?.active || !this.ahRun || (this.ahRun.status !== "active" && this.ahRun.status !== "cleared")) return; const reward = pickup.ahLoot; pickup.disableBody(true, true); pickup.destroy(); if (reward.kind === "exp") this.ahRun.expEarned += reward.value; if (reward.kind === "bones") this.ahRun.bonesEarned += reward.value; if (reward.kind === "scrap") this.ahRun.scrapEarned += reward.value; if (reward.kind === "equipment") this.ahRun.equipmentDrops += reward.value; updateHud(this); showMessage(this, "+" + reward.value + " " + reward.label); }
  function clearEncounter(scene) { const run = scene.ahRun; if (!run || run.status !== "active") return; run.status = "cleared"; setRelayState(scene, "available"); showMessage(scene, "ALL CHASERS CLEARED - RELAY UNLOCKED"); updateContext(scene); }
  function activateRelay(scene) { const run = scene.ahRun; if (!run || run.status !== "cleared" || scene.ahContext !== "relay") return; run.relayActivated = true; setRelayState(scene, "activated"); setExitState(scene, true); completeRun(scene); }
  function submitCompletionOnce(run) { if (S.completedRunIds.has(run.runId)) return false; S.completedRunIds.add(run.runId); return true; }
  function completeRun(scene) { const run = scene.ahRun; if (!run || run.status !== "cleared" || !run.relayActivated) return; run.status = "completed"; run.duration = Math.max(0, Math.round((Date.now() - run.startedAt) / 1000)); scene.ahPlayerControl = false; scene.ahEnemies.children.iterate(enemy => enemy?.setVelocity?.(0, 0)); submitCompletionOnce(run); setContext(scene, null); showResultPanel(run, false); }
  function damagePlayer(scene, damage) { const run = scene.ahRun; if (!run || run.status !== "active") return; const activeRunId = run.runId; run.playerHP = Math.max(0, run.playerHP - damage); scene.ahPlayer.setTint(0xff8da7); scene.time.delayedCall(90, () => scene.ahRun?.runId === activeRunId && scene.ahPlayer?.active && scene.ahPlayer.clearTint()); updateHud(scene); if (run.playerHP === 0) failRun(scene); }
  function updateEnemy(scene, enemy, time) { const run = scene.ahRun, p = scene.ahPlayer; if (!run || run.status !== "active" || !p?.active || !enemy?.active || enemy.ahCombat?.dead) return; const dx = p.x - enemy.x, dy = p.y - enemy.y, distanceSq = dx * dx + dy * dy; if (distanceSq <= COMBAT.enemyAttackRange * COMBAT.enemyAttackRange) { enemy.setVelocity(0, 0); setAnimation(enemy, "ah-relay-chaser", enemy.ahDirection, false); if (time >= enemy.ahCombat.nextAttackAt) { enemy.ahCombat.nextAttackAt = time + COMBAT.enemyAttackCooldownMs; damagePlayer(scene, COMBAT.enemyDamage); } } else if (distanceSq <= COMBAT.enemyAggroRange * COMBAT.enemyAggroRange) { const distance = Math.sqrt(distanceSq) || 1, vx = dx / distance * COMBAT.enemySpeed, vy = dy / distance * COMBAT.enemySpeed; enemy.setVelocity(vx, vy); setAnimation(enemy, "ah-relay-chaser", Math.abs(vx) > Math.abs(vy) ? (vx < 0 ? "left" : "right") : (vy < 0 ? "up" : "down"), true); } else { enemy.setVelocity(0, 0); setAnimation(enemy, "ah-relay-chaser", enemy.ahDirection, false); } updateEnemyUi(enemy); }
  function updateCombat(scene, time) { const target = nearestEnemy(scene); if (target) { scene.ahTargetRing.setPosition(target.enemy.x, target.enemy.y + 20).setVisible(true); scene.ahTargetLabel.setText("TARGET  " + Math.ceil(Math.sqrt(target.distanceSq))); } else { scene.ahTargetRing.setVisible(false); scene.ahTargetLabel.setText(scene.ahRun?.status === "cleared" || scene.ahRun?.status === "completed" ? "AREA CLEAR" : ""); } scene.ahEnemies.children.iterate(enemy => updateEnemy(scene, enemy, time)); }
  function failRun(scene) { const run = scene.ahRun; if (!run || run.status !== "active") return; run.status = "failed"; run.relayActivated = false; scene.ahPlayerControl = false; scene.ahEnemies.children.iterate(enemy => enemy?.setVelocity?.(0, 0)); scene.ahPlayer.disableBody(true, true); scene.input.enabled = false; setContext(scene, null); showResultPanel(run, true); }
  function removeResultPanel() { S.root?.querySelector(".ah-sector-result")?.remove(); }
  function showResultPanel(run, failed) { removeResultPanel(); const panel = document.createElement("section"); panel.className = "ah-sector-result"; if (failed) panel.innerHTML = `<div class="ah-sector-result__card ah-sector-result__card--failed"><div class="ah-sector-result__eyebrow">RELAY FRINGE 01</div><h2>RUN FAILED</h2><p>Signal approach collapsed. No local rewards were claimed.</p><div class="ah-sector-result__actions"><button type="button" data-sector-run-action="restart">RESTART SECTOR</button><button type="button" data-sector-run-action="map">RETURN TO MAP</button></div></div>`; else panel.innerHTML = `<div class="ah-sector-result__card"><div class="ah-sector-result__eyebrow">RUN COMPLETE</div><h2>${SECTOR.displayName}</h2><dl><dt>Time</dt><dd>${run.duration}s</dd><dt>Enemies</dt><dd>${run.enemiesKilled} / ${run.requiredEnemies}</dd><dt>EXP</dt><dd>+${run.expEarned}</dd><dt>Bones</dt><dd>+${run.bonesEarned}</dd><dt>Scrap</dt><dd>+${run.scrapEarned}</dd><dt>Equipment</dt><dd>${run.equipmentDrops}</dd></dl><div class="ah-sector-result__actions"><button type="button" data-sector-run-action="again">RUN AGAIN</button><button type="button" data-sector-run-action="map">RETURN TO MAP</button></div></div>`; S.root?.querySelector(".ah-exploration-room__stage")?.appendChild(panel); }

  function shutdown() { const scene = this; scene.ahResetInput?.(); scene.ahStop?.(); scene.ahJoyHit?.off("pointerdown", scene.ahOnJoyDown); scene.ahAttackHit?.off("pointerdown", scene.ahOnAttackDown); scene.ahRelayHit?.off("pointerdown", scene.ahOnRelayDown); scene.ahDashHit?.off("pointerdown", scene.ahOnDashDown); scene.input?.off("pointermove", scene.ahOnMove); scene.input?.off("pointerup", scene.ahOnUp); scene.input?.off("gameout", scene.ahOnGameOut); scene.ahMessageTimer?.remove?.(false); scene.ahLegacyTelegraph?.destroy?.(); removeResultPanel(); }
  function preload() { trace("SCENE_PRELOAD"); Object.values(ASSETS).filter(asset => ![ASSETS.player, ASSETS.chaser, ASSETS.loot, ASSETS.slash].includes(asset)).forEach(asset => this.load.image(asset.key, asset.url)); this.load.spritesheet(ASSETS.player.key, ASSETS.player.url, { frameWidth: 256, frameHeight: 256 }); this.load.spritesheet(ASSETS.chaser.key, ASSETS.chaser.url, { frameWidth: 256, frameHeight: 256 }); this.load.spritesheet(ASSETS.loot.key, ASSETS.loot.url, { frameWidth: 256, frameHeight: 256 }); this.load.spritesheet(ASSETS.slash.key, ASSETS.slash.url, { frameWidth: 256, frameHeight: 256 }); }
  function create() { try { trace("SCENE_CREATE_START"); this.physics.world.setBounds(0, 0, WORLD.width, WORLD.height); makeAnimations(this); buildWorld(this); createControls(this); createKeyboard(this); this.cameras.main.setBounds(0, 0, WORLD.width, WORLD.height); this.cameras.main.startFollow(this.ahPlayer, true, .13, .13); this.cameras.main.setRoundPixels(true); this.sys.events.once("shutdown", shutdown, this); S.scene = this; startRun(this); S.canvas = S.canvasParent?.querySelector("canvas") || this.game.canvas; if (!S.canvas) throw new Error("Relay canvas was not created"); S.canvas.setAttribute("aria-label", "Relay Fringe 01 playable signal approach"); trace("ROOM_READY"); settle(true); } catch (error) { settle(false, error); } }
  function update(time) { if (S.closing || this.ahPaused || !this.ahPlayer) return; updatePlayer(this); updateCombat(this, time); updateLegacySentinel(this, time); updateLegacyDashControl(this); updateContext(this); const k = this.ahKeys; if (global.Phaser.Input.Keyboard.JustDown(k?.attack) || global.Phaser.Input.Keyboard.JustDown(k?.space)) playerAttack(this); if (global.Phaser.Input.Keyboard.JustDown(k?.dash)) legacyDash(this); if (global.Phaser.Input.Keyboard.JustDown(k?.interact)) { if (this.ahContext === "relay") activateRelay(this); else if (this.ahContext === "exit") void close(); } if (global.Phaser.Input.Keyboard.JustDown(k?.escape)) void close(); }
  function settle(ok, error) { const resolve = S.resolveReady, reject = S.rejectReady; S.resolveReady = S.rejectReady = null; if (S.readyTimer) { clearTimeout(S.readyTimer); S.readyTimer = null; } if (ok) resolve?.(true); else reject?.(error || new Error("Relay room unavailable")); }
  function createGame() { return new Promise((resolve, reject) => { S.resolveReady = resolve; S.rejectReady = reject; S.readyTimer = setTimeout(() => settle(false, new Error("Relay room timed out")), 9000); try { S.game = new global.Phaser.Game({ type: global.Phaser.AUTO, parent: CANVAS_ID, width: S.canvasParent.clientWidth, height: S.canvasParent.clientHeight, backgroundColor: "#071019", audio: { noAudio: true }, input: { activePointers: 4, touch: { capture: true } }, scale: { mode: global.Phaser.Scale.RESIZE, width: S.canvasParent.clientWidth, height: S.canvasParent.clientHeight }, physics: { default: "arcade", arcade: { gravity: { x: 0, y: 0 }, debug: !!global.DBG } }, render: { roundPixels: true, powerPreference: "low-power" }, scene: { preload, create, update } }); } catch (error) { settle(false, error); } }); }
  async function cleanup(options) { settle(false); unbindEvents(); const scene = S.scene; scene?.ahResetInput?.(); scene?.ahStop?.(); if (scene?.input) scene.input.enabled = false; const game = S.game; S.game = null; S.scene = null; if (game) try { game.destroy(true); } catch (error) { log("destroy", error); } S.canvasParent?.replaceChildren(); unregisterNavigation(!!options?.fromNavigation); S.root?.remove(); S.root = S.canvasParent = S.loading = null; S.ready = false; restorePage(); }
  async function runOpen(generation) { try { injectCSS(); buildShell(); lockPage(); readInsets(); bindEvents(); registerNavigation(); if (!global.Phaser?.Game) throw new Error("Phaser unavailable"); const ready = await createGame(); if (!ready || generation !== S.generation || S.closing) return false; S.loading.hidden = true; S.ready = true; return true; } catch (error) { await cleanup(); throw error; } }
  function init(deps = {}) { S.tg = deps.tg || S.tg || global.Telegram?.WebApp || null; S.apiPost = deps.apiPost || S.apiPost; if (typeof deps.dbg === "boolean" || typeof deps.dbg === "function") S.dbg = deps.dbg; if (typeof deps.trace === "function") S.trace = deps.trace; S.devPreview = deps.devPreview === true; return API; }
  function open(options = {}) { if (String(options.sectorId || "") !== SECTOR.sectorId) return Promise.resolve(false); if (S.opening) return S.opening; if (isOpen() && S.ready) return Promise.resolve(true); S.onClose = typeof options.onClose === "function" ? options.onClose : null; S.closing = false; const generation = ++S.generation; const task = runOpen(generation); const wrapped = task.finally(() => { if (S.opening === wrapped) S.opening = null; }); S.opening = wrapped; return wrapped; }
  async function close(options) { if (S.closing) return false; if (!S.root && !S.game && !S.opening) return false; S.closing = true; ++S.generation; const after = S.onClose; S.onClose = null; try { await cleanup(options); await Promise.resolve(after?.()); return true; } finally { S.closing = false; } }
  function isOpen() { return !!(S.root && document.documentElement.contains(S.root) && !S.closing); }
  const API = { init, open, close, isOpen, sectorConfig: SECTOR };
  global.AlphaExplorationRoom = API;
})(window);
